/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import { axios } from '../axios';

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P
) => any
  ? P
  : never;

/**
 * @summary Shuts down the node
 */
export const nodeShutdown = (options?: SecondParameter<typeof axios>) => {
  return axios<void>({ url: `/node/shutdown`, method: 'post' }, options);
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type NodeShutdownResult = NonNullable<
  Awaited<ReturnType<typeof nodeShutdown>>
>;
