/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { Summary } from './summary';
import type { Transactions } from './transactions';

export interface AddressInfo {
  summary: Summary;
  transactions: Transactions;
}
