/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface AssetSummary {
  /** Token ID */
  tokenId: string;
  /** Amount of tokens */
  amount: bigint;
  /** Name of a token */
  name?: string;
  /** Number of decimal places */
  decimals?: number;
}
export const bigIntsAssetSummary: Array<string> = ['amount'];
