/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface AssetSummary {
  /** Token ID */
  tokenId: string;
  /** Amount of tokens */
  amount: number;
  /** Name of a token */
  name?: string;
  /** Number of decimal places */
  decimals?: number;
}
