/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface BadRequest {
  status: number;
  reason: string;
}
export const bigIntsBadRequest = [];
