/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface BalanceInfo {
  /** Address */
  address: string;
  /** Balance in nanoERG */
  balance: bigint;
}
