/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface BalanceInfo {
  /** Address */
  address: string;
  /** Balance in nanoERG */
  balance: bigint;
}
export const bigIntsBalanceInfo = ['balance'];
