/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { FullBlockInfo } from './fullBlockInfo';
import { bigIntsFullBlockInfo } from './fullBlockInfo';
import type { BlockReferencesInfo } from './blockReferencesInfo';

import { bigIntsBlockReferencesInfo } from './blockReferencesInfo';

export interface BlockSummary {
  block: FullBlockInfo;
  references: BlockReferencesInfo;
}

export const bigIntsBlockSummary = [
  ...bigIntsFullBlockInfo.map((item) => `block.${item}`),
  ...bigIntsBlockReferencesInfo.map((item) => `references.${item}`),
];
