/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { BlockReferencesInfo } from './blockReferencesInfo';
import { bigIntsBlockReferencesInfo } from './blockReferencesInfo';
import type { FullBlockInfo } from './fullBlockInfo';
import { bigIntsFullBlockInfo } from './fullBlockInfo';

export interface BlockSummary {
  block: FullBlockInfo;
  references: BlockReferencesInfo;
}

export const bigIntsBlockSummary: Array<string> = [
  ...bigIntsFullBlockInfo.map((item) =>
    item === '' ? 'block' : `block.${item}`,
  ),
  ...bigIntsBlockReferencesInfo.map((item) =>
    item === '' ? 'references' : `references.${item}`,
  ),
];
