/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface BlockChainInfo {
  /** Network protocol version */
  version: string;
  /** Total supply in nanoErgs */
  supply: bigint;
  /** Average number of transactions per block */
  transactionAverage: number;
  /** Network hash rate */
  hashRate: string;
}
export const bigIntsBlockChainInfo: Array<string> = ['supply'];
