/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface BlockChainInfo {
  /** Network protocol version */
  version: string;
  /** Total supply in nanoErgs */
  supply: bigint;
  /** Average number of transactions per block */
  transactionAverage: bigint;
  /** Network hash rate */
  hashRate: string;
}
