/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface DataInputInfo {
  /** ID of the corresponding box */
  id: string;
  /** Number of nanoErgs in the corresponding box */
  value?: bigint;
  index: number;
  /** ID of the transaction this data input was used in */
  transactionId: string;
  /** ID of the transaction outputting corresponding box */
  outputTransactionId?: string;
  outputIndex?: number;
  /** Decoded address of the corresponding box holder */
  address?: string;
}
export const bigIntsDataInputInfo = ['value'];
