/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { OutputInfo } from './outputInfo';

export interface DexSellOrderInfo {
  outputInfo: OutputInfo;
  /** ERG amount */
  amount: number;
}
