/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { OutputInfo } from './outputInfo';
import { bigIntsOutputInfo } from './outputInfo';

export interface DexSellOrderInfo {
  outputInfo: OutputInfo;
  /** ERG amount */
  amount: bigint;
}

export const bigIntsDexSellOrderInfo: Array<string> = [
  ...bigIntsOutputInfo.map((item) =>
    item === '' ? 'outputInfo' : `outputInfo.${item}`,
  ),
  'amount',
];
