/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0TransactionsUnconfirmedParams = {
  offset?: number;
  limit?: number;
  sortBy?: string;
  sortDirection?: string;
};
export const bigIntsGetApiV0TransactionsUnconfirmedParams = [];
