/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0DexTokensP1UnspentbuyordersParams = {
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  limit?: number;
};
export const bigIntsGetApiV0DexTokensP1UnspentbuyordersParams: Array<string> =
  [];
