/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0AddressesP1TransactionsParams = {
  offset?: number;
  limit?: number;
  /**
   * Hide excessive data
   */
  concise?: boolean;
};
