/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0AddressesBalancesParams = {
  offset?: bigint;
  limit?: bigint;
};
