/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0TransactionsSinceP1Params = {
  offset?: number;
  limit?: number;
};
export const bigIntsGetApiV0TransactionsSinceP1Params = [];
