/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0AddressesP1Params = {
  minConfirmations?: number;
};
export const bigIntsGetApiV0AddressesP1Params: Array<string> = [];
