/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export type GetApiV0TransactionsSinceP1Params = {
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  limit?: number;
};
export const bigIntsGetApiV0TransactionsSinceP1Params: Array<string> = [];
