/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { PowSolutionInfo } from './powSolutionInfo';
import type { Tuple3ByteByteByte } from './tuple3ByteByteByte';

export interface HeaderInfo {
  /** Block/header ID */
  id: string;
  /** ID of the parental block/header */
  parentId: string;
  /** Version of the header */
  version: number;
  /** Block/header height */
  height: number;
  /** Block/header epoch (Epochs are enumerated from 0) */
  epoch: number;
  /** Block/header difficulty */
  difficulty: string;
  /** Hex-encoded root of the corresponding AD proofs */
  adProofsRoot: string;
  /** Hex-encoded root of the corresponding state */
  stateRoot: string;
  /** Hex-encoded root of the corresponding transactions */
  transactionsRoot: string;
  /** Timestamp the block/header was created */
  timestamp: number;
  /** Encoded required difficulty */
  nBits: number;
  /** Size of the header in bytes */
  size: number;
  /** Hex-encoded hash of the corresponding extension */
  extensionHash: string;
  powSolutions: PowSolutionInfo;
  votes: Tuple3ByteByteByte;
}
