/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface InputInfo {
  /** ID of the corresponding box */
  id: string;
  /** Number of nanoErgs in the corresponding box */
  value?: number;
  /** Index of the input in a transaction */
  index: number;
  /** Hex-encoded serialized sigma proof */
  spendingProof?: string;
  /** ID of the transaction this input was used in */
  transactionId: string;
  /** ID of the transaction outputting corresponding box */
  outputTransactionId?: string;
  /** Index of the output corresponding this input */
  outputIndex?: number;
  /** Decoded address of the corresponding box holder */
  address?: string;
}
