/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { TransactionInfo } from './transactionInfo';

export interface ItemsTransactionInfo {
  /** Items in selection */
  items?: TransactionInfo[];
  /** Total qty of items */
  total: number;
}
