/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { UTransactionInfo } from './uTransactionInfo';

import { bigIntsUTransactionInfo } from './uTransactionInfo';

export interface ItemsUTransactionInfo {
  /** Items in selection */
  items?: UTransactionInfo[];
  /** Total qty of items */
  total: number;
}
export const bigIntsItemsUTransactionInfo = [
  ...bigIntsUTransactionInfo.map((item) => `items.${item}`),
];
