/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface MiniBlockInfo {
  /** Block ID */
  id: string;
  /** Block height */
  height: bigint;
}
