/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface MiniBlockInfo {
  /** Block ID */
  id: string;
  /** Block height */
  height: number;
}
export const bigIntsMiniBlockInfo: Array<string> = [];
