/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface NotFound {
  status: number;
  reason: string;
}
export const bigIntsNotFound: Array<string> = [];
