/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { AssetInstanceInfo } from './assetInstanceInfo';
import type { OutputInfoAdditionalRegisters } from './outputInfoAdditionalRegisters';

export interface OutputInfo {
  /** Id of the box */
  id: string;
  /** Id of the transaction that created the box */
  txId: string;
  /** Value of the box in nanoERG */
  value: number;
  /** Index of the output in a transaction */
  index: number;
  /** Height at which the box was created */
  creationHeight: number;
  /** Serialized ergo tree */
  ergoTree: string;
  /** An address derived from ergo tree */
  address: string;
  assets?: AssetInstanceInfo[];
  additionalRegisters: OutputInfoAdditionalRegisters;
  /** Transaction ID */
  spentTransactionId?: string;
  mainChain: boolean;
}
