/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { AssetInstanceInfo } from './assetInstanceInfo';
import { bigIntsAssetInstanceInfo } from './assetInstanceInfo';
import type { OutputInfoAdditionalRegisters } from './outputInfoAdditionalRegisters';

import { bigIntsOutputInfoAdditionalRegisters } from './outputInfoAdditionalRegisters';

export interface OutputInfo {
  /** Id of the box */
  id: string;
  /** Id of the transaction that created the box */
  txId: string;
  /** Value of the box in nanoERG */
  value: bigint;
  /** Index of the output in a transaction */
  index: number;
  /** Height at which the box was created */
  creationHeight: number;
  /** Serialized ergo tree */
  ergoTree: string;
  /** An address derived from ergo tree */
  address: string;
  assets?: AssetInstanceInfo[];
  additionalRegisters: OutputInfoAdditionalRegisters;
  /** Transaction ID */
  spentTransactionId?: string;
  mainChain: boolean;
}

export const bigIntsOutputInfo = [
  'value',
  ...bigIntsAssetInstanceInfo.map((item) =>
    item === '' ? 'assets' : `assets.${item}`
  ),
  ...bigIntsOutputInfoAdditionalRegisters.map((item) =>
    item === '' ? 'additionalRegisters' : `additionalRegisters.${item}`
  ),
];
