/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface PowSolutionInfo {
  /** Miner public key */
  pk: string;
  /** Hex-encoded string */
  w: string;
  /** Hex-encoded string */
  n: string;
  /** Autolykos.d */
  d: string;
}
