/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

/**
 * Proof extension (key->value dictionary)
 */
export type SpendingProofInfoExtension = { [key: string]: string };
