/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { SpendingProofInfoExtension } from './spendingProofInfoExtension';

export interface SpendingProofInfo {
  /** Hex-encoded serialized sigma proof */
  proofBytes?: string;
  /** Proof extension (key->value dictionary) */
  extension: SpendingProofInfoExtension;
}
