/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface StatsSummary {
  /** Number of block within defined period */
  blocksCount: bigint;
  /** Avg. block time within defined period */
  blocksAvgTime: bigint;
  /** Total number of coins transferred within defined period */
  totalCoins: bigint;
  /** Total number of transactions within defined period */
  totalTransactionsCount: bigint;
  /** Total amount of tx fees within defined period */
  totalFee: bigint;
  /** Total amount of unspent outputs within defined period */
  totalOutput: string;
  /** Total amount of estimated outputs within defined period */
  estimatedOutput: string;
  /** Total miner revenue within defined period */
  totalMinerRevenue: bigint;
  /** Percent of tx fees in total amount of coins within defined period */
  percentEarnedTransactionsFees: number;
  /** Percent of miner rewards in total amount of coins within defined period */
  percentTransactionVolume: number;
  /** Avg. transaction fee within defined period */
  costPerTx: bigint;
  /** Latest network difficulty */
  lastDifficulty: string;
  /** Total network hashrate within defined period */
  totalHashrate: string;
}

export const bigIntsStatsSummary = [
  'blocksCount',
  'blocksAvgTime',
  'totalCoins',
  'totalTransactionsCount',
  'totalFee',
  'totalMinerRevenue',
  'costPerTx',
];
