/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface StatsSummary {
  /** Number of block within defined period */
  blocksCount: number;
  /** Avg. block time within defined period */
  blocksAvgTime: number;
  /** Total number of coins transferred within defined period */
  totalCoins: number;
  /** Total number of transactions within defined period */
  totalTransactionsCount: number;
  /** Total amount of tx fees within defined period */
  totalFee: number;
  /** Total amount of unspent outputs within defined period */
  totalOutput: string;
  /** Total amount of estimated outputs within defined period */
  estimatedOutput: string;
  /** Total miner revenue within defined period */
  totalMinerRevenue: number;
  /** Percent of tx fees in total amount of coins within defined period */
  percentEarnedTransactionsFees: number;
  /** Percent of miner rewards in total amount of coins within defined period */
  percentTransactionVolume: number;
  /** Avg. transaction fee within defined period */
  costPerTx: number;
  /** Latest network difficulty */
  lastDifficulty: string;
  /** Total network hashrate within defined period */
  totalHashrate: string;
}
