/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface Summary {
  /** Address identifier */
  id: string;
}
export const bigIntsSummary = [];
