/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { AssetSummary } from './assetSummary';

import { bigIntsAssetSummary } from './assetSummary';

export interface Transactions {
  /** Number of confirmed txs */
  confirmed: number;
  /** Total number of received nanoErgs */
  totalReceived: string;
  /** Confirmed balance of address in nanoErgs */
  confirmedBalance: bigint;
  /** Total (confirmed + unconfirmed) balance of address in nanoErgs */
  totalBalance: bigint;
  /** Confirmed tokens balance of address */
  confirmedTokensBalance?: AssetSummary[];
  /** Total (confirmed + unconfirmed) tokens balance of address */
  totalTokensBalance?: AssetSummary[];
}

export const bigIntsTransactions = [
  'confirmedBalance',
  'totalBalance',
  ...bigIntsAssetSummary.map((item) => `confirmedTokensBalance.${item}`),
  ...bigIntsAssetSummary.map((item) => `totalTokensBalance.${item}`),
];
