/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { MiniBlockInfo } from './miniBlockInfo';
import { bigIntsMiniBlockInfo } from './miniBlockInfo';
import type { InputInfo } from './inputInfo';
import { bigIntsInputInfo } from './inputInfo';
import type { DataInputInfo } from './dataInputInfo';
import { bigIntsDataInputInfo } from './dataInputInfo';
import type { OutputInfo } from './outputInfo';
import { bigIntsOutputInfo } from './outputInfo';
import type { TxStats } from './txStats';

import { bigIntsTxStats } from './txStats';

export interface TransactionSummary {
  /** Transaction ID */
  id: string;
  miniBlockInfo: MiniBlockInfo;
  /** Timestamp the transaction got into the network */
  timestamp: bigint;
  /** Index of a transaction inside a block */
  index: number;
  /** Number of transaction confirmations */
  confirmationsCount: number;
  inputs?: InputInfo[];
  dataInputs?: DataInputInfo[];
  outputs?: OutputInfo[];
  /** Size of a transaction in bytes */
  size: number;
  ioSummary: TxStats;
}

export const bigIntsTransactionSummary = [
  ...bigIntsMiniBlockInfo.map((item) => `miniBlockInfo.${item}`),
  'timestamp',
  ...bigIntsInputInfo.map((item) => `inputs.${item}`),
  ...bigIntsDataInputInfo.map((item) => `dataInputs.${item}`),
  ...bigIntsOutputInfo.map((item) => `outputs.${item}`),
  ...bigIntsTxStats.map((item) => `ioSummary.${item}`),
];
