/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { DataInputInfo } from './dataInputInfo';
import { bigIntsDataInputInfo } from './dataInputInfo';
import type { InputInfo } from './inputInfo';
import { bigIntsInputInfo } from './inputInfo';
import type { OutputInfo } from './outputInfo';
import { bigIntsOutputInfo } from './outputInfo';

export interface TransactionInfo {
  /** Transaction ID */
  id: string;
  /** ID of the corresponding header */
  headerId: string;
  /** Height of the block the transaction was included in */
  inclusionHeight: number;
  /** Timestamp the transaction got into the network */
  timestamp: bigint;
  /** Index of a transaction inside a block */
  index: number;
  /** Number of transaction confirmations */
  confirmationsCount: number;
  inputs?: InputInfo[];
  dataInputs?: DataInputInfo[];
  outputs?: OutputInfo[];
}

export const bigIntsTransactionInfo: Array<string> = [
  'timestamp',
  ...bigIntsInputInfo.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`,
  ),
  ...bigIntsDataInputInfo.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`,
  ),
  ...bigIntsOutputInfo.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`,
  ),
];
