/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { AssetSummary } from './assetSummary';

export interface Transactions {
  /** Number of confirmed txs */
  confirmed: bigint;
  /** Total number of received nanoErgs */
  totalReceived: string;
  /** Confirmed balance of address in nanoErgs */
  confirmedBalance: bigint;
  /** Total (confirmed + unconfirmed) balance of address in nanoErgs */
  totalBalance: bigint;
  /** Confirmed tokens balance of address */
  confirmedTokensBalance?: AssetSummary[];
  /** Total (confirmed + unconfirmed) tokens balance of address */
  totalTokensBalance?: AssetSummary[];
}
