/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

/**
 * Block votes (3 bytes)
 */
export interface Tuple3ByteByteByte {
  _1: bigint;
  _2: bigint;
  _3: bigint;
}
