/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

/**
 * Block votes (3 bytes)
 */
export interface Tuple3ByteByteByte {
  _1: number;
  _2: number;
  _3: number;
}
export const bigIntsTuple3ByteByteByte = [];
