/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface TxStats {
  /** Total amount of coins transferred by transaction */
  totalCoinsTransferred: bigint;
  /** Total amount of fee in the transaction */
  totalFee: bigint;
  /** Amount of nanoERGs ber byte in transaction */
  feePerByte: bigint;
}
