/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

export interface UDataInputInfo {
  /** Id of the corresponding box */
  id: string;
  /** ID of the transaction this data input was used in */
  transactionId: string;
  /** Amount of nanoERGs in the corresponding box */
  value?: bigint;
  /** Index of the input in a transaction */
  index: bigint;
  /** ID of the output transaction */
  outputTransactionId?: string;
  /** Index of the output corresponding this input */
  outputIndex?: bigint;
  /** Address */
  address?: string;
}
