/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { AssetInstanceInfo } from './assetInstanceInfo';
import type { UOutputInfoAdditionalRegisters } from './uOutputInfoAdditionalRegisters';

export interface UOutputInfo {
  /** Id of the corresponding box */
  id: string;
  /** Id of the transaction that created the box */
  txId: string;
  /** Amount of nanoERGs containing in the box */
  value: bigint;
  index: bigint;
  /** Approximate height the box was created */
  creationHeight: bigint;
  /** Encoded script */
  ergoTree: string;
  /** Address derived from ErgoTree */
  address?: string;
  assets?: AssetInstanceInfo[];
  /** Arbitrary key->value dictionary */
  additionalRegisters: UOutputInfoAdditionalRegisters;
}
