/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */

/**
 * Arbitrary key->value dictionary
 */
export type UOutputInfoAdditionalRegisters = { [key: string]: string };
export const bigIntsUOutputInfoAdditionalRegisters = [];
