/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { UInputInfo } from './uInputInfo';
import { bigIntsUInputInfo } from './uInputInfo';
import type { UDataInputInfo } from './uDataInputInfo';
import { bigIntsUDataInputInfo } from './uDataInputInfo';
import type { UOutputInfo } from './uOutputInfo';
import { bigIntsUOutputInfo } from './uOutputInfo';
import type { TxStats } from './txStats';

import { bigIntsTxStats } from './txStats';

export interface UTransactionSummary {
  /** Transaction ID */
  id: string;
  inputs?: UInputInfo[];
  dataInputs?: UDataInputInfo[];
  outputs?: UOutputInfo[];
  /** Approximate time this transaction appeared in the network */
  creationTimestamp: bigint;
  /** Size of the transaction in bytes */
  size: number;
  ioSummary: TxStats;
}

export const bigIntsUTransactionSummary = [
  ...bigIntsUInputInfo.map((item) => `inputs.${item}`),
  ...bigIntsUDataInputInfo.map((item) => `dataInputs.${item}`),
  ...bigIntsUOutputInfo.map((item) => `outputs.${item}`),
  'creationTimestamp',
  ...bigIntsTxStats.map((item) => `ioSummary.${item}`),
];
