/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { UInputInfo } from './uInputInfo';
import type { UDataInputInfo } from './uDataInputInfo';
import type { UOutputInfo } from './uOutputInfo';
import type { TxStats } from './txStats';

export interface UTransactionSummary {
  /** Transaction ID */
  id: string;
  inputs?: UInputInfo[];
  dataInputs?: UDataInputInfo[];
  outputs?: UOutputInfo[];
  /** Approximate time this transaction appeared in the network */
  creationTimestamp: number;
  /** Size of the transaction in bytes */
  size: number;
  ioSummary: TxStats;
}
