/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v0
 * OpenAPI spec version: 1.0
 */
import type { TxStats } from './txStats';
import { bigIntsTxStats } from './txStats';
import type { UDataInputInfo } from './uDataInputInfo';
import { bigIntsUDataInputInfo } from './uDataInputInfo';
import type { UInputInfo } from './uInputInfo';
import { bigIntsUInputInfo } from './uInputInfo';
import type { UOutputInfo } from './uOutputInfo';
import { bigIntsUOutputInfo } from './uOutputInfo';

export interface UTransactionSummary {
  /** Transaction ID */
  id: string;
  inputs?: UInputInfo[];
  dataInputs?: UDataInputInfo[];
  outputs?: UOutputInfo[];
  /** Approximate time this transaction appeared in the network */
  creationTimestamp: bigint;
  /** Size of the transaction in bytes */
  size: number;
  ioSummary: TxStats;
}

export const bigIntsUTransactionSummary: Array<string> = [
  ...bigIntsUInputInfo.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`,
  ),
  ...bigIntsUDataInputInfo.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`,
  ),
  ...bigIntsUOutputInfo.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`,
  ),
  'creationTimestamp',
  ...bigIntsTxStats.map((item) =>
    item === '' ? 'ioSummary' : `ioSummary.${item}`,
  ),
];
