/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Koios API
 * Koios is best described as a Decentralized and Elastic RESTful query layer for exploring data on Cardano blockchain to consume within applications/wallets/explorers/etc. This page not only provides an OpenAPI Spec for live implementation, but also ability to execute live demo from client browser against each endpoint with pre-filled examples.

# API Usage

The endpoints served by Koios can be browsed from the left side bar of this site. You will find that almost each endpoint has an example that you can `Try` and will help you get an example in shell using cURL. For public queries, you do not need to register yourself - you can simply use them as per the examples provided on individual endpoints. But in addition, the [PostgREST API](https://postgrest.org/en/stable/api.html) used underneath provides a handful of features that can be quite handy for you to improve your queries to directly grab very specific information pertinent to your calls, reducing data you download and process.

## Vertical Filtering

Instead of returning entire row, you can elect which rows you would like to fetch from the endpoint by using the `select` parameter with corresponding columns separated by commas. See example below (first is complete information for tip, while second command gives us 3 columns we are interested in):<br><br>

``` bash
curl "https://api.koios.rest/api/v1/tip"

# [{"hash":"4d44c8a453e677f933c3df42ebcf2fe45987c41268b9cfc9b42ae305e8c3d99a","epoch_no":317,"abs_slot":51700871,"epoch_slot":120071,"block_height":6806994,"block_time":1643267162}]

curl "https://api.koios.rest/api/v1/blocks?select=epoch_no,epoch_slot,block_height"

# [{"epoch_no":317,"epoch_slot":120071,"block_height":6806994}]
```

## Horizontal Filtering

You can filter the returned output based on specific conditions using operators against a column within returned result. Consider an example where you would want to query blocks minted in first 3 minutes of epoch 250 (i.e. epoch_slot was less than 180). To do so your query would look like below:<br><br>
``` bash
curl "https://api.koios.rest/api/v1/blocks?epoch_no=eq.250&epoch_slot=lt.180"

# [{"hash":"8fad2808ac6b37064a0fa69f6fe065807703d5235a57442647bbcdba1c02faf8","epoch_no":250,"abs_slot":22636942,"epoch_slot":142,"block_height":5385757,"block_time":1614203233,"tx_count":65,"vrf_key":"vrf_vk14y9pjprzlsjvjt66mv5u7w7292sxp3kn4ewhss45ayjga5vurgaqhqknuu","pool":null,"op_cert_counter":2},
#  {"hash":"9d33b02badaedc0dedd0d59f3e0411e5fb4ac94217fb5ee86719e8463c570e16","epoch_no":250,"abs_slot":22636800,"epoch_slot":0,"block_height":5385756,"block_time":1614203091,"tx_count":10,"vrf_key":"vrf_vk1dkfsejw3h2k7tnguwrauqfwnxa7wj3nkp3yw2yw3400c4nlkluwqzwvka6","pool":null,"op_cert_counter":2}]
```

Here, we made use of `eq.` operator to denote a filter of "value equal to" against `epoch_no` column. Similarly, we added a filter using `lt.` operator to denote a filter of "values lower than" against `epoch_slot` column. You can find a complete list of operators supported in PostgREST documentation (commonly used ones extracted below):

|Abbreviation|In PostgreSQL|Meaning                                    |
|------------|-------------|-------------------------------------------|
|eq          |`=`          |equals                                     |
|gt          |`>`          |greater than                               |
|gte         |`>=`         |greater than or equal                      |
|lt          |`<`          |less than                                  |
|lte         |`<=`         |less than or equal                         |
|neq         |`<>` or `!=` |not equal                                  |
|like        |`LIKE`       |LIKE operator (use * in place of %)        |
|in          |`IN`         |one of a list of values, e.g. `?a=in.("hi,there","yes,you")`|
|is          |`IS`         |checking for exact equality (null,true,false,unknown)|
|cs          |`@>`         |contains e.g. `?tags=cs.{example, new}`    |
|cd          |`<@`         |contained in e.g. `?values=cd.{1,2,3}`     |
|not         |`NOT`        |negates another operator                   |
|or          |`OR`         |logical `OR` operator                      |
|and         |`AND`        |logical `AND` operator                     |

## Pagination (offset/limit)

When you query any endpoint in PostgREST, the number of observations returned will be limited to a maximum of 1000 rows (set via `max-rows` config option in the `grest.conf` file. This - however - is a result of a paginated call, wherein the [ up to ] 1000 records you see without any parameters is the first page. If you want to see the next 1000 results, you can always append `offset=1000` to view the next set of results. But what if 1000 is too high for your use-case and you want smaller page? Well, you can specify a smaller limit using parameter `limit`, which will see shortly in an example below. The obvious question at this point that would cross your mind is - how do I know if I need to offset and what range I am querying? This is where headers come in to your aid.  

The default headers returned by PostgREST will include a `Content-Range` field giving a range of observations returned. For large tables, this range could include a wildcard `*` as it is expensive to query exact count of observations from endpoint. But if you would like to get an estimate count without overloading servers, PostgREST can utilise Postgres's own maintenance thread results (which maintain stats for each table) to provide you a count, by specifying a header `"Preferred: count=estimated"`.  

Sounds confusing? Let's see this in practice, to hopefully make it easier.
Consider a simple case where I want query `blocks` endpoint for `block_height` column and focus on `content-range` header to monitor the rows we discussed above.<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?select=block_height" -I | grep -i content-range

# content-range: 0-999/*

```

As we can see above, the number of observations returned was 1000 (range being 0-999), but the total size was not queried to avoid wait times. Now, let's modify this default behaviour to query rows beyond the first 999, but this time - also add another clause to limit results by 500. We can do this using `offset=1000` and `limit=500` as below:<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?select=block_height&offset=1000&limit=500" -I | grep -i content-range

# content-range: 1000-1499/*

```

The above methods for pagination are very useful to keep some of the queries light as well as process the output in smaller pages, making better use of your resources and respecting server timeouts for response times.
However, note that due to the complex nature of some queries that require pre-processing before being subjected to paginations, these may not always be helpful to avoid server timeouts.

## Ordering

You can set a sorting order for returned queries against specific column(s).
Consider example where you want to check `epoch_no` and `epoch_slot` for the first 5 blocks created by a particular pool, i.e. you can set order to ascending based on block_height column and add horizontal filter for that pool ID as below:<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?pool=eq.pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc&order=block_height.asc&limit=5"

# [{"hash":"610b4c7bbebeeb212bd002885048cc33154ba29f39919d62a3d96de05d315706","epoch_no":236,"abs_slot":16594295,"epoch_slot":5495,"block_height":5086774,"block_time":1608160586,"tx_count":1,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"d93d1db5275329ab695d30c06a35124038d8d9af64fc2b0aa082b8aa43da4164","epoch_no":236,"abs_slot":16597729,"epoch_slot":8929,"block_height":5086944,"block_time":1608164020,"tx_count":7,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"dc9496eae64294b46f07eb20499ae6dae4d81fdc67c63c354397db91bda1ee55","epoch_no":236,"abs_slot":16598058,"epoch_slot":9258,"block_height":5086962,"block_time":1608164349,"tx_count":1,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"6ebc7b734c513bc19290d96ca573a09cac9503c5a349dd9892b9ab43f917f9bd","epoch_no":236,"abs_slot":16601491,"epoch_slot":12691,"block_height":5087097,"block_time":1608167782,"tx_count":0,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"2eac97548829fc312858bc56a40f7ce3bf9b0ca27ee8530283ccebb3963de1c0","epoch_no":236,"abs_slot":16602308,"epoch_slot":13508,"block_height":5087136,"block_time":1608168599,"tx_count":1,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1}]
```

## Response Formats

You can get the results from the PostgREST endpoints in CSV or JSON formats. The default response format will always be JSON, but if you'd like to switch, you can do so by specifying header `'Accept: text/csv'` or `'Accept: application/json'`.
Below is an example of JSON/CSV output making use of above to print first in JSON (default), and then override response format to CSV.<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?select=epoch_no,epoch_slot,block_time&limit=3"

# [{"epoch_no":318,"epoch_slot":27867,"block_time":1643606958},
# {"epoch_no":318,"epoch_slot":27841,"block_time":1643606932},
# {"epoch_no":318,"epoch_slot":27839,"block_time":1643606930}]

curl -s "https://api.koios.rest/api/v1/blocks?select=epoch_no,epoch_slot,block_time&limit=3" -H "Accept: text/csv"

# epoch_no,epoch_slot,block_time
# 318,28491,1643607582
# 318,28479,1643607570
# 318,28406,1643607497

```

## Limits

While use of Koios is completely free and there are no registration requirements to the usage, the monitoring layer will only restrict spam requests that can potentially cause high amount of load to backends. The emphasis is on using list of objects first, and then [bulk where available] query specific objects to drill down where possible - which forms higher performance results to consumer as well as instance provider. Some basic protection against patterns that could cause unexpected resource spikes are protected as per below:

  - Burst Limit: A single IP can query an endpoint up to 100 times within 10 seconds (that's about 8.64 million requests within a day). The sleep time if a limit is crossed is minimal (60 seconds) for that IP - during which, the monitoring layer will return HTTP Status `429 - Too many requests`.  
  - Pagination/Limits: Any query results fetched will be paginated by 1000 records (you can reduce limit and or control pagination offsets on URL itself, see API > Pagination section for more details).
  - Query timeout: If a query from server takes more than 30 seconds, it will return a HTTP Status of `504 - Gateway timeout`. This is because we would want to ensure you're using the queries optimally, and more often than not - it would indicate that particular endpoint is not optimised (or the network connectivity is not optimal between servers).
  - Payload size limit: Koios supports sending bulk objects to reduce networking costs as well as number of calls users spent. However, this can also become an easy attack surface. Thus, we've had to add a strict limit for request body size to be limited to 1kb for public and 5kb for registered tiers.

Yet, there may be cases where the above restrictions may need exceptions (for example, an explorer or a wallet might need more connections than above - going beyond the Burst Limit). For such cases, it is best to approach the team and we can work towards a solution.

# Authentication

While Koios public tier remains unauthenticated and allows queries without any authentication, it has low limits to prevent actions against an erroraneous query/loop from a consumer. There is also a Free tier which requires setting up Bearer Auth token that is linked to the owner's wallet account (which can be connected to via [Koios website](https://koios.rest/pricing/Pricing.html) ).
The examples across this API site already [supports authentication](/#auth), for you to use in the queries.

# Community projects

A big thank you to the following projects who are already starting to use Koios from early days. A list of tools, libraries and projects utilising Koios (atleast those who'd like to be named) can be found [here](https://www.koios.rest/community.html)

 * OpenAPI spec version: v1.2.0
 */
import type {
  AccountAddresses,
  AccountAssets,
  AccountHistory,
  AccountInfo,
  AccountList,
  AccountRewards,
  AccountTxsParams,
  AccountUpdates,
  AddressAssets,
  AddressInfo,
  AddressTxs,
  AddressTxsBody,
  AssetAddresses,
  AssetAddressesParams,
  AssetHistory,
  AssetHistoryParams,
  AssetInfo,
  AssetList,
  AssetListBody,
  AssetListWithExtendedBody,
  AssetNftAddress,
  AssetNftAddressParams,
  AssetSummary,
  AssetSummaryParams,
  AssetTokenRegistry,
  AssetTxsParams,
  BlockHashesBody,
  BlockInfo,
  BlockTxInfo,
  BlockTxInfoBody,
  BlockTxs,
  Blocks,
  CliProtocolParams,
  CommitteeInfo,
  CommitteeVotes,
  CommitteeVotesParams,
  CredentialTxsBody,
  CredentialUtxosBody,
  DatumHashesBody,
  DatumInfo,
  DrepDelegators,
  DrepDelegatorsParams,
  DrepEpochSummary,
  DrepEpochSummaryParams,
  DrepIdBulkBody,
  DrepInfo,
  DrepList,
  DrepMetadata,
  DrepUpdates,
  DrepUpdatesParams,
  DrepVotes,
  DrepVotesParams,
  EpochBlockProtocols,
  EpochBlockProtocolsParams,
  EpochInfo,
  EpochInfoParams,
  EpochParams,
  EpochParamsParams,
  Genesis,
  OgmiosBody,
  Ogmiostip,
  ParamUpdates,
  PaymentAddressesBody,
  PaymentAddressesWithExtendedBody,
  PolicyAssetAddresses,
  PolicyAssetAddressesParams,
  PolicyAssetInfo,
  PolicyAssetInfoParams,
  PolicyAssetList,
  PolicyAssetListParams,
  PolicyAssetMints,
  PolicyAssetMintsParams,
  PoolBlocks,
  PoolBlocksParams,
  PoolDelegators,
  PoolDelegatorsHistory,
  PoolDelegatorsHistoryParams,
  PoolDelegatorsParams,
  PoolHistoryInfo,
  PoolHistoryParams,
  PoolIdsBody,
  PoolIdsOptionalBody,
  PoolInfo,
  PoolList,
  PoolMetadata,
  PoolRegistrations,
  PoolRegistrationsParams,
  PoolRelays,
  PoolRetirementsParams,
  PoolSnapshot,
  PoolStakeSnapshotParams,
  PoolUpdates,
  PoolUpdatesParams,
  PoolVotes,
  PoolVotesParams,
  ProposalList,
  ProposalVotes,
  ProposalVotesParams,
  ProposalVotingSummary,
  ProposalVotingSummaryParams,
  ReserveWithdrawals,
  ScriptHashesBody,
  ScriptInfo,
  ScriptList,
  ScriptRedeemers,
  ScriptRedeemersParams,
  ScriptUtxosParams,
  StakeAddressesBody,
  StakeAddressesWithEpochNoBody,
  StakeAddressesWithExtendedBody,
  StakeAddressesWithFirstOnlyAndEmptyBody,
  Tip,
  Totals,
  TotalsParams,
  TxCbor,
  TxIdsBody,
  TxInfo,
  TxInfoBody,
  TxMetadata,
  TxMetalabels,
  TxStatus,
  TxUtxos,
  TxbinBody,
  UtxoInfos,
  UtxoRefsWithExtendedBody,
  VoterProposalListParams,
} from '../types';

import {
  bigIntsAccountAddresses,
  bigIntsAccountAssets,
  bigIntsAccountHistory,
  bigIntsAccountInfo,
  bigIntsAccountList,
  bigIntsAccountRewards,
  bigIntsAccountUpdates,
  bigIntsAddressAssets,
  bigIntsAddressInfo,
  bigIntsAddressTxs,
  bigIntsAssetAddresses,
  bigIntsAssetHistory,
  bigIntsAssetInfo,
  bigIntsAssetList,
  bigIntsAssetNftAddress,
  bigIntsAssetSummary,
  bigIntsAssetTokenRegistry,
  bigIntsBlockInfo,
  bigIntsBlockTxInfo,
  bigIntsBlockTxs,
  bigIntsBlocks,
  bigIntsCliProtocolParams,
  bigIntsCommitteeInfo,
  bigIntsCommitteeVotes,
  bigIntsDatumInfo,
  bigIntsDrepDelegators,
  bigIntsDrepEpochSummary,
  bigIntsDrepInfo,
  bigIntsDrepList,
  bigIntsDrepMetadata,
  bigIntsDrepUpdates,
  bigIntsDrepVotes,
  bigIntsEpochBlockProtocols,
  bigIntsEpochInfo,
  bigIntsEpochParams,
  bigIntsGenesis,
  bigIntsOgmiostip,
  bigIntsParamUpdates,
  bigIntsPolicyAssetAddresses,
  bigIntsPolicyAssetInfo,
  bigIntsPolicyAssetList,
  bigIntsPolicyAssetMints,
  bigIntsPoolBlocks,
  bigIntsPoolDelegators,
  bigIntsPoolDelegatorsHistory,
  bigIntsPoolHistoryInfo,
  bigIntsPoolInfo,
  bigIntsPoolList,
  bigIntsPoolMetadata,
  bigIntsPoolRegistrations,
  bigIntsPoolRelays,
  bigIntsPoolSnapshot,
  bigIntsPoolUpdates,
  bigIntsPoolVotes,
  bigIntsProposalList,
  bigIntsProposalVotes,
  bigIntsProposalVotingSummary,
  bigIntsReserveWithdrawals,
  bigIntsScriptInfo,
  bigIntsScriptList,
  bigIntsScriptRedeemers,
  bigIntsTip,
  bigIntsTotals,
  bigIntsTxCbor,
  bigIntsTxInfo,
  bigIntsTxMetadata,
  bigIntsTxMetalabels,
  bigIntsTxStatus,
  bigIntsTxUtxos,
  bigIntsUtxoInfos,
} from '../types';

import {
  createAxiosInstanceWithHeaders,
  JsonFieldBigintFactory,
} from '../axios';

export const getKoiosAPI = (url: string, authToken?: string) => {
  const instance = createAxiosInstanceWithHeaders(
    url,
    authToken
      ? {
          Authorization: `Bearer ${authToken}`,
        }
      : {}
  );
  /**
   * Get the tip info about the latest block seen by chain
   * @summary Query Chain Tip
   */
  const tip = () => {
    return instance<Tip>({
      url: `/tip`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsTip),
    });
  };

  /**
   * Get the Genesis parameters used to start specific era on chain
   * @summary Get Genesis info
   */
  const genesis = () => {
    return instance<Genesis>({
      url: `/genesis`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsGenesis),
    });
  };

  /**
   * Get the circulating utxo, treasury, rewards, supply and reserves in lovelace for specified epoch, all epochs if empty
   * @summary Get historical tokenomic stats
   */
  const totals = (params?: TotalsParams) => {
    return instance<Totals>({
      url: `/totals`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsTotals),
    });
  };

  /**
   * Get all parameter update proposals submitted to the chain starting Shelley era
   * @summary Param Update Proposals
   */
  const paramUpdates = () => {
    return instance<ParamUpdates>({
      url: `/param_updates`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsParamUpdates),
    });
  };

  /**
   * Get Current Protocol Parameters as published by cardano-cli. Note that the output schema of this command is unfortunately fluid on cardano-node and may vary between CLI versions/era. Accordingly, the returned output for this endpoint is left as raw JSON (single row) and any filtering to output should be done on client-side
   * @summary CLI Protocol Parameters
   */
  const cliProtocolParams = () => {
    return instance<CliProtocolParams>({
      url: `/cli_protocol_params`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsCliProtocolParams),
    });
  };

  /**
   * List of all withdrawals from reserves against stake accounts
   * @summary Reserve Withdrawals
   */
  const reserveWithdrawals = () => {
    return instance<ReserveWithdrawals>({
      url: `/reserve_withdrawals`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsReserveWithdrawals),
    });
  };

  /**
   * List of all withdrawals from treasury against stake accounts
   * @summary Treasury Withdrawals
   */
  const treasuryWithdrawals = () => {
    return instance<ReserveWithdrawals>({
      url: `/treasury_withdrawals`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsReserveWithdrawals),
    });
  };

  /**
   * Get the epoch information, all epochs if no epoch specified
   * @summary Epoch Information
   */
  const epochInfo = (params?: EpochInfoParams) => {
    return instance<EpochInfo>({
      url: `/epoch_info`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsEpochInfo),
    });
  };

  /**
   * Get the protocol parameters for specific epoch, returns information about all epochs if no epoch specified
   * @summary Epoch's Protocol Parameters
   */
  const epochParams = (params?: EpochParamsParams) => {
    return instance<EpochParams>({
      url: `/epoch_params`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsEpochParams),
    });
  };

  /**
   * Get the information about block protocol distribution in epoch
   * @summary Epoch's Block Protocols
   */
  const epochBlockProtocols = (params?: EpochBlockProtocolsParams) => {
    return instance<EpochBlockProtocols>({
      url: `/epoch_block_protocols`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsEpochBlockProtocols),
    });
  };

  /**
   * Get summarised details about all blocks (paginated - latest first)
   * @summary Block List
   */
  const blocks = () => {
    return instance<Blocks>({
      url: `/blocks`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsBlocks),
    });
  };

  /**
   * Get detailed information about a specific block
   * @summary Block Information
   */
  const blockInfo = (blockHashesBody: BlockHashesBody) => {
    return instance<BlockInfo>({
      url: `/block_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: blockHashesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsBlockInfo),
    });
  };

  /**
   * Get a list of all transactions included in provided blocks
   * @summary Block Transactions
   */
  const blockTxs = (blockHashesBody: BlockHashesBody) => {
    return instance<BlockTxs>({
      url: `/block_txs`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: blockHashesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsBlockTxs),
    });
  };

  /**
   * Get detailed information about transaction(s) for requested blocks
   * @summary Block Transactions (Detailed Info)
   */
  const blockTxInfo = (blockTxInfoBody: BlockTxInfoBody) => {
    return instance<BlockTxInfo>({
      url: `/block_tx_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: blockTxInfoBody,
      transformResponse: JsonFieldBigintFactory(bigIntsBlockTxInfo),
    });
  };

  /**
   * Get UTxO set for requested UTxO references
   * @summary UTxO Info
   */
  const utxoInfo = (utxoRefsWithExtendedBody: UtxoRefsWithExtendedBody) => {
    return instance<UtxoInfos>({
      url: `/utxo_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: utxoRefsWithExtendedBody,
      transformResponse: JsonFieldBigintFactory(bigIntsUtxoInfos),
    });
  };

  /**
   * Get raw transaction(s) in CBOR format
   * @summary Raw Transaction (CBOR)
   */
  const txCbor = (txIdsBody: TxIdsBody) => {
    return instance<TxCbor>({
      url: `/tx_cbor`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: txIdsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsTxCbor),
    });
  };

  /**
   * Get detailed information about transaction(s)
   * @summary Transaction Information
   */
  const txInfo = (txInfoBody: TxInfoBody) => {
    return instance<TxInfo>({
      url: `/tx_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: txInfoBody,
      transformResponse: JsonFieldBigintFactory(bigIntsTxInfo),
    });
  };

  /**
   * Get metadata information (if any) for given transaction(s)
   * @summary Transaction Metadata
   */
  const txMetadata = (txIdsBody: TxIdsBody) => {
    return instance<TxMetadata>({
      url: `/tx_metadata`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: txIdsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsTxMetadata),
    });
  };

  /**
   * Get a list of all transaction metalabels
   * @summary Transaction Metadata Labels
   */
  const txMetalabels = () => {
    return instance<TxMetalabels>({
      url: `/tx_metalabels`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsTxMetalabels),
    });
  };

  /**
   * Submit an already serialized transaction to the network.
   * @summary Submit Transaction
   */
  const submittx = (txbinBody: TxbinBody) => {
    return instance<string>({
      url: `/submittx`,
      method: 'POST',
      headers: { 'Content-Type': 'application/cbor' },
      data: txbinBody,
    });
  };

  /**
   * Get the number of block confirmations for a given transaction hash list
   * @summary Transaction Status
   */
  const txStatus = (txIdsBody: TxIdsBody) => {
    return instance<TxStatus>({
      url: `/tx_status`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: txIdsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsTxStatus),
    });
  };

  /**
   * Get UTxO set (inputs/outputs) of transactions [DEPRECATED - Use /utxo_info instead].
   * @deprecated
   * @summary Transaction UTxOs
   */
  const txUtxos = (txIdsBody: TxIdsBody) => {
    return instance<TxUtxos>({
      url: `/tx_utxos`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: txIdsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsTxUtxos),
    });
  };

  /**
   * Get address info - balance, associated stake address (if any) and UTxO set for given addresses
   * @summary Address Information
   */
  const addressInfo = (paymentAddressesBody: PaymentAddressesBody) => {
    return instance<AddressInfo>({
      url: `/address_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: paymentAddressesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAddressInfo),
    });
  };

  /**
   * Get UTxO set for given addresses
   * @summary Address UTXOs
   */
  const addressUtxos = (
    paymentAddressesWithExtendedBody: PaymentAddressesWithExtendedBody
  ) => {
    return instance<UtxoInfos>({
      url: `/address_utxos`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: paymentAddressesWithExtendedBody,
      transformResponse: JsonFieldBigintFactory(bigIntsUtxoInfos),
    });
  };

  /**
   * Get UTxO details for requested payment credentials
   * @summary UTxOs from payment credentials
   */
  const credentialUtxos = (credentialUtxosBody: CredentialUtxosBody) => {
    return instance<UtxoInfos>({
      url: `/credential_utxos`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: credentialUtxosBody,
      transformResponse: JsonFieldBigintFactory(bigIntsUtxoInfos),
    });
  };

  /**
   * Get the transaction hash list of input address array, optionally filtering after specified block height (inclusive)
   * @summary Address Transactions
   */
  const addressTxs = (addressTxsBody: AddressTxsBody) => {
    return instance<AddressTxs>({
      url: `/address_txs`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addressTxsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAddressTxs),
    });
  };

  /**
   * Get the transaction hash list of input payment credential array, optionally filtering after specified block height (inclusive)
   * @summary Transactions from payment credentials
   */
  const credentialTxs = (credentialTxsBody: CredentialTxsBody) => {
    return instance<AddressTxs>({
      url: `/credential_txs`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: credentialTxsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAddressTxs),
    });
  };

  /**
   * Get the list of all the assets (policy, name and quantity) for given addresses
   * @summary Address Assets
   */
  const addressAssets = (paymentAddressesBody: PaymentAddressesBody) => {
    return instance<AddressAssets>({
      url: `/address_assets`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: paymentAddressesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAddressAssets),
    });
  };

  /**
   * Get a list of all stake addresses that have atleast 1 transaction
   * @summary Account List
   */
  const accountList = () => {
    return instance<AccountList>({
      url: `/account_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsAccountList),
    });
  };

  /**
   * Get the account information for given stake addresses
   * @summary Account Information
   */
  const accountInfo = (stakeAddressesBody: StakeAddressesBody) => {
    return instance<AccountInfo>({
      url: `/account_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountInfo),
    });
  };

  /**
   * Get the cached account information for given stake addresses (effective for performance query against registered accounts)
   * @summary Account Information (Cached)
   */
  const accountInfoCached = (stakeAddressesBody: StakeAddressesBody) => {
    return instance<AccountInfo>({
      url: `/account_info_cached`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountInfo),
    });
  };

  /**
   * Get a list of all UTxOs for given stake addresses (account)s
   * @summary UTxOs for stake addresses (accounts)
   */
  const accountUtxos = (
    stakeAddressesWithExtendedBody: StakeAddressesWithExtendedBody
  ) => {
    return instance<UtxoInfos>({
      url: `/account_utxos`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesWithExtendedBody,
      transformResponse: JsonFieldBigintFactory(bigIntsUtxoInfos),
    });
  };

  /**
   * Get a list of all Txs for a given stake address (account)
   * @summary Account Txs
   */
  const accountTxs = (params: AccountTxsParams) => {
    return instance<AddressTxs>({
      url: `/account_txs`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsAddressTxs),
    });
  };

  /**
   * Get the full rewards history (including MIR) for given stake addresses
   * @summary Account Rewards
   */
  const accountRewards = (
    stakeAddressesWithEpochNoBody: StakeAddressesWithEpochNoBody
  ) => {
    return instance<AccountRewards>({
      url: `/account_rewards`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesWithEpochNoBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountRewards),
    });
  };

  /**
   * Get the account updates (registration, deregistration, delegation and withdrawals) for given stake addresses
   * @summary Account Updates
   */
  const accountUpdates = (stakeAddressesBody: StakeAddressesBody) => {
    return instance<AccountUpdates>({
      url: `/account_updates`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountUpdates),
    });
  };

  /**
   * Get all addresses associated with given staking accounts
   * @summary Account Addresses
   */
  const accountAddresses = (
    stakeAddressesWithFirstOnlyAndEmptyBody: StakeAddressesWithFirstOnlyAndEmptyBody
  ) => {
    return instance<AccountAddresses>({
      url: `/account_addresses`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesWithFirstOnlyAndEmptyBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountAddresses),
    });
  };

  /**
   * Get the native asset balance for a given stake address
   * @summary Account Assets
   */
  const accountAssets = (stakeAddressesBody: StakeAddressesBody) => {
    return instance<AccountAssets>({
      url: `/account_assets`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountAssets),
    });
  };

  /**
   * Get the staking history of given stake addresses (accounts)
   * @summary Account History
   */
  const accountHistory = (
    stakeAddressesWithEpochNoBody: StakeAddressesWithEpochNoBody
  ) => {
    return instance<AccountHistory>({
      url: `/account_history`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeAddressesWithEpochNoBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAccountHistory),
    });
  };

  /**
   * Get the list of all native assets (paginated)
   * @summary Asset List
   */
  const assetList = () => {
    return instance<AssetList>({
      url: `/asset_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsAssetList),
    });
  };

  /**
   * Get the list of asset under the given policy (including balances)
   * @summary Policy Asset List
   */
  const policyAssetList = (params: PolicyAssetListParams) => {
    return instance<PolicyAssetList>({
      url: `/policy_asset_list`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPolicyAssetList),
    });
  };

  /**
   * Get a list of assets registered via token registry on github
   * @summary Asset Token Registry
   */
  const assetTokenRegistry = () => {
    return instance<AssetTokenRegistry>({
      url: `/asset_token_registry`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsAssetTokenRegistry),
    });
  };

  /**
   * Get the information of a list of assets including first minting & token registry metadata
   * @summary Asset Information (Bulk)
   */
  const assetInfo = (assetListBody: AssetListBody) => {
    return instance<AssetInfo>({
      url: `/asset_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assetListBody,
      transformResponse: JsonFieldBigintFactory(bigIntsAssetInfo),
    });
  };

  /**
   * Get the UTXO information of a list of assets including
   * @summary Asset UTXOs
   */
  const assetUtxos = (assetListWithExtendedBody: AssetListWithExtendedBody) => {
    return instance<UtxoInfos>({
      url: `/asset_utxos`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: assetListWithExtendedBody,
      transformResponse: JsonFieldBigintFactory(bigIntsUtxoInfos),
    });
  };

  /**
   * Get the mint/burn history of an asset
   * @summary Asset History
   */
  const assetHistory = (params: AssetHistoryParams) => {
    return instance<AssetHistory>({
      url: `/asset_history`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsAssetHistory),
    });
  };

  /**
   * Get the list of all addresses holding a given asset <br><br> `Note - Due to cardano's UTxO design and usage from projects, asset to addresses map can be infinite. Thus, for a small subset of active projects with millions of transactions, these might end up with timeouts (HTTP code 504) on free layer. Such large-scale projects are free to subscribe to query layers to have a dedicated cache table for themselves served via Koios.`
   * @summary Asset Addresses
   */
  const assetAddresses = (params: AssetAddressesParams) => {
    return instance<AssetAddresses>({
      url: `/asset_addresses`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsAssetAddresses),
    });
  };

  /**
   * Get the address where specified NFT currently reside on.
   * @summary NFT Address
   */
  const assetNftAddress = (params: AssetNftAddressParams) => {
    return instance<AssetNftAddress>({
      url: `/asset_nft_address`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsAssetNftAddress),
    });
  };

  /**
   * Get the list of addresses with quantity for each asset on the given policy <br><br> `Note - Due to cardano's UTxO design and usage from projects, asset to addresses map can be infinite. Thus, for a small subset of active projects with millions of transactions, these might end up with timeouts (HTTP code 504) on free layer. Such large-scale projects are free to subscribe to query layers to have a dedicated cache table for themselves served via Koios.`
   * @summary Policy Asset Address List
   */
  const policyAssetAddresses = (params: PolicyAssetAddressesParams) => {
    return instance<PolicyAssetAddresses>({
      url: `/policy_asset_addresses`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPolicyAssetAddresses),
    });
  };

  /**
   * Get the information for all assets under the same policy
   * @summary Policy Asset Information
   */
  const policyAssetInfo = (params: PolicyAssetInfoParams) => {
    return instance<PolicyAssetInfo>({
      url: `/policy_asset_info`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPolicyAssetInfo),
    });
  };

  /**
   * Get a list of mint or burn count details for all assets minted under a policy
   * @summary Policy Asset Mints
   */
  const policyAssetMints = (params: PolicyAssetMintsParams) => {
    return instance<PolicyAssetMints>({
      url: `/policy_asset_mints`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPolicyAssetMints),
    });
  };

  /**
   * Get the summary of an asset (total transactions exclude minting/total wallets include only wallets with asset balance)
   * @summary Asset Summary
   */
  const assetSummary = (params: AssetSummaryParams) => {
    return instance<AssetSummary>({
      url: `/asset_summary`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsAssetSummary),
    });
  };

  /**
   * Get the list of current or all asset transaction hashes (newest first)
   * @summary Asset Transactions
   */
  const assetTxs = (params: AssetTxsParams) => {
    return instance<AddressTxs>({
      url: `/asset_txs`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsAddressTxs),
    });
  };

  /**
   * Summary of voting power and DRep count for each epoch
   * @summary DReps Epoch Summary
   */
  const drepEpochSummary = (params?: DrepEpochSummaryParams) => {
    return instance<DrepEpochSummary>({
      url: `/drep_epoch_summary`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsDrepEpochSummary),
    });
  };

  /**
   * List of all active delegated representatives (DReps)
   * @summary DReps List
   */
  const drepList = () => {
    return instance<DrepList>({
      url: `/drep_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsDrepList),
    });
  };

  /**
   * Get detailed information about requested delegated representatives (DReps)
   * @summary DReps Info
   */
  const drepInfo = (drepIdBulkBody: DrepIdBulkBody) => {
    return instance<DrepInfo>({
      url: `/drep_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: drepIdBulkBody,
      transformResponse: JsonFieldBigintFactory(bigIntsDrepInfo),
    });
  };

  /**
   * List metadata for requested delegated representatives (DReps)
   * @summary DReps Metadata
   */
  const drepMetadata = (drepIdBulkBody: DrepIdBulkBody) => {
    return instance<DrepMetadata>({
      url: `/drep_metadata`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: drepIdBulkBody,
      transformResponse: JsonFieldBigintFactory(bigIntsDrepMetadata),
    });
  };

  /**
   * List of updates for requested (or all) delegated representatives (DReps)
   * @summary DReps Updates
   */
  const drepUpdates = (params?: DrepUpdatesParams) => {
    return instance<DrepUpdates>({
      url: `/drep_updates`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsDrepUpdates),
    });
  };

  /**
   * List of all votes casted by requested delegated representative (DRep)
   * @summary DReps Votes
   */
  const drepVotes = (params: DrepVotesParams) => {
    return instance<DrepVotes>({
      url: `/drep_votes`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsDrepVotes),
    });
  };

  /**
   * List of all delegators to requested delegated representative (DRep).
   * @summary DReps Delegators
   */
  const drepDelegators = (params: DrepDelegatorsParams) => {
    return instance<DrepDelegators>({
      url: `/drep_delegators`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsDrepDelegators),
    });
  };

  /**
   * Information about active committee and its members
   * @summary Committee Information
   */
  const committeeInfo = () => {
    return instance<CommitteeInfo>({
      url: `/committee_info`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsCommitteeInfo),
    });
  };

  /**
   * List of all votes casted by given committee member or collective
   * @summary Committee Votes
   */
  const committeeVotes = (params?: CommitteeVotesParams) => {
    return instance<CommitteeVotes>({
      url: `/committee_votes`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsCommitteeVotes),
    });
  };

  /**
   * List of all governance proposals
   * @summary Proposals List
   */
  const proposalList = () => {
    return instance<ProposalList>({
      url: `/proposal_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsProposalList),
    });
  };

  /**
   * List of all governance proposals for specified DRep, SPO or Committee credential
   * @summary Voter's Proposal List
   */
  const voterProposalList = (params: VoterProposalListParams) => {
    return instance<ProposalList>({
      url: `/voter_proposal_list`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsProposalList),
    });
  };

  /**
   * Summary of votes for given proposal
   * @summary Proposal Voting Summary
   */
  const proposalVotingSummary = (params: ProposalVotingSummaryParams) => {
    return instance<ProposalVotingSummary>({
      url: `/proposal_voting_summary`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsProposalVotingSummary),
    });
  };

  /**
   * List of all votes cast on specified governance action
   * @summary Proposal Votes
   */
  const proposalVotes = (params: ProposalVotesParams) => {
    return instance<ProposalVotes>({
      url: `/proposal_votes`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsProposalVotes),
    });
  };

  /**
   * List of brief info for all pools
   * @summary Pool List
   */
  const poolList = () => {
    return instance<PoolList>({
      url: `/pool_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsPoolList),
    });
  };

  /**
   * Current pool statuses and details for a specified list of pool ids
   * @summary Pool Information
   */
  const poolInfo = (poolIdsBody: PoolIdsBody) => {
    return instance<PoolInfo>({
      url: `/pool_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: poolIdsBody,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolInfo),
    });
  };

  /**
   * Returns Mark, Set and Go stake snapshots for the selected pool, useful for leaderlog calculation
   * @summary Pool Stake Snapshot
   */
  const poolStakeSnapshot = (params: PoolStakeSnapshotParams) => {
    return instance<PoolSnapshot>({
      url: `/pool_stake_snapshot`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolSnapshot),
    });
  };

  /**
   * Return information about live delegators for a given pool.
   * @summary Pool Delegators List
   */
  const poolDelegators = (params: PoolDelegatorsParams) => {
    return instance<PoolDelegators>({
      url: `/pool_delegators`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolDelegators),
    });
  };

  /**
   * Return information about active delegators (incl. history) for a given pool and epoch number (all epochs if not specified).
   * @summary Pool Delegators History
   */
  const poolDelegatorsHistory = (params: PoolDelegatorsHistoryParams) => {
    return instance<PoolDelegatorsHistory>({
      url: `/pool_delegators_history`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolDelegatorsHistory),
    });
  };

  /**
   * Return information about blocks minted by a given pool for all epochs (or _epoch_no if provided)
   * @summary Pool Blocks
   */
  const poolBlocks = (params: PoolBlocksParams) => {
    return instance<PoolBlocks>({
      url: `/pool_blocks`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolBlocks),
    });
  };

  /**
   * Return information about pool stake, block and reward history in a given epoch _epoch_no (or all epochs that pool existed for, in descending order if no _epoch_no was provided)
   * @summary Pool Stake, Block and Reward History
   */
  const poolHistory = (params: PoolHistoryParams) => {
    return instance<PoolHistoryInfo>({
      url: `/pool_history`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolHistoryInfo),
    });
  };

  /**
   * Return all pool updates for all pools or only updates for specific pool if specified
   * @summary Pool Updates (History)
   */
  const poolUpdates = (params?: PoolUpdatesParams) => {
    return instance<PoolUpdates>({
      url: `/pool_updates`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolUpdates),
    });
  };

  /**
   * Return all pool registrations initiated in the requested epoch
   * @summary Pool Registrations
   */
  const poolRegistrations = (params?: PoolRegistrationsParams) => {
    return instance<PoolRegistrations>({
      url: `/pool_registrations`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolRegistrations),
    });
  };

  /**
   * Return all pool retirements initiated in the requested epoch
   * @summary Pool Retirements
   */
  const poolRetirements = (params?: PoolRetirementsParams) => {
    return instance<PoolRegistrations>({
      url: `/pool_retirements`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolRegistrations),
    });
  };

  /**
   * A list of registered relays for all pools
   * @summary Pool Relays
   */
  const poolRelays = () => {
    return instance<PoolRelays>({
      url: `/pool_relays`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsPoolRelays),
    });
  };

  /**
   * List of all votes casted by a pool
   * @summary Pool Votes
   */
  const poolVotes = (params: PoolVotesParams) => {
    return instance<PoolVotes>({
      url: `/pool_votes`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolVotes),
    });
  };

  /**
   * Metadata (on & off-chain) for all pools
   * @summary Pool Metadata
   */
  const poolMetadata = (poolIdsOptionalBody: PoolIdsOptionalBody) => {
    return instance<PoolMetadata>({
      url: `/pool_metadata`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: poolIdsOptionalBody,
      transformResponse: JsonFieldBigintFactory(bigIntsPoolMetadata),
    });
  };

  /**
   * List of script information for given script hashes
   * @summary Script Information
   */
  const scriptInfo = (scriptHashesBody: ScriptHashesBody) => {
    return instance<ScriptInfo>({
      url: `/script_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: scriptHashesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsScriptInfo),
    });
  };

  /**
   * List of all existing native script hashes along with their creation transaction hashes
   * @summary Native Script List
   */
  const nativeScriptList = () => {
    return instance<ScriptList>({
      url: `/native_script_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsScriptList),
    });
  };

  /**
   * List of all existing Plutus script hashes along with their creation transaction hashes
   * @summary Plutus Script List
   */
  const plutusScriptList = () => {
    return instance<ScriptList>({
      url: `/plutus_script_list`,
      method: 'GET',
      transformResponse: JsonFieldBigintFactory(bigIntsScriptList),
    });
  };

  /**
   * List of all redeemers for a given script hash
   * @summary Script Redeemers
   */
  const scriptRedeemers = (params: ScriptRedeemersParams) => {
    return instance<ScriptRedeemers>({
      url: `/script_redeemers`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsScriptRedeemers),
    });
  };

  /**
   * List of all UTXOs for a given script hash
   * @summary Script UTXOs
   */
  const scriptUtxos = (params: ScriptUtxosParams) => {
    return instance<UtxoInfos>({
      url: `/script_utxos`,
      method: 'GET',
      params,
      transformResponse: JsonFieldBigintFactory(bigIntsUtxoInfos),
    });
  };

  /**
   * List of datum information for given datum hashes
   * @summary Datum Information
   */
  const datumInfo = (datumHashesBody: DatumHashesBody) => {
    return instance<DatumInfo>({
      url: `/datum_info`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: datumHashesBody,
      transformResponse: JsonFieldBigintFactory(bigIntsDatumInfo),
    });
  };

  /**
 * Query the current tip of the Network.

<br>
<div style="background-color: #222; padding: 12px 0px 12px 12px;border-left: 5px solid  rgb(173, 44, 44);font-size: var(--font-size-regular);">
We do support transparent forwarding for various methods from Ogmios, you can read about those <a href="#tag--Ogmios">here</a>.
</div>

 * @summary Query Example
 */
  const ogmios = (ogmiosBody: OgmiosBody) => {
    return instance<Ogmiostip>({
      url: `/ogmios`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: ogmiosBody,
      transformResponse: JsonFieldBigintFactory(bigIntsOgmiostip),
    });
  };

  return {
    tip,
    genesis,
    totals,
    paramUpdates,
    cliProtocolParams,
    reserveWithdrawals,
    treasuryWithdrawals,
    epochInfo,
    epochParams,
    epochBlockProtocols,
    blocks,
    blockInfo,
    blockTxs,
    blockTxInfo,
    utxoInfo,
    txCbor,
    txInfo,
    txMetadata,
    txMetalabels,
    submittx,
    txStatus,
    txUtxos,
    addressInfo,
    addressUtxos,
    credentialUtxos,
    addressTxs,
    credentialTxs,
    addressAssets,
    accountList,
    accountInfo,
    accountInfoCached,
    accountUtxos,
    accountTxs,
    accountRewards,
    accountUpdates,
    accountAddresses,
    accountAssets,
    accountHistory,
    assetList,
    policyAssetList,
    assetTokenRegistry,
    assetInfo,
    assetUtxos,
    assetHistory,
    assetAddresses,
    assetNftAddress,
    policyAssetAddresses,
    policyAssetInfo,
    policyAssetMints,
    assetSummary,
    assetTxs,
    drepEpochSummary,
    drepList,
    drepInfo,
    drepMetadata,
    drepUpdates,
    drepVotes,
    drepDelegators,
    committeeInfo,
    committeeVotes,
    proposalList,
    voterProposalList,
    proposalVotingSummary,
    proposalVotes,
    poolList,
    poolInfo,
    poolStakeSnapshot,
    poolDelegators,
    poolDelegatorsHistory,
    poolBlocks,
    poolHistory,
    poolUpdates,
    poolRegistrations,
    poolRetirements,
    poolRelays,
    poolVotes,
    poolMetadata,
    scriptInfo,
    nativeScriptList,
    plutusScriptList,
    scriptRedeemers,
    scriptUtxos,
    datumInfo,
    ogmios,
  };
};
export type TipResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['tip']>>
>;
export type GenesisResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['genesis']>>
>;
export type TotalsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['totals']>>
>;
export type ParamUpdatesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['paramUpdates']>>
>;
export type CliProtocolParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['cliProtocolParams']>>
>;
export type ReserveWithdrawalsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['reserveWithdrawals']>>
>;
export type TreasuryWithdrawalsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['treasuryWithdrawals']>>
>;
export type EpochInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['epochInfo']>>
>;
export type EpochParamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['epochParams']>>
>;
export type EpochBlockProtocolsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['epochBlockProtocols']>>
>;
export type BlocksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['blocks']>>
>;
export type BlockInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['blockInfo']>>
>;
export type BlockTxsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['blockTxs']>>
>;
export type BlockTxInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['blockTxInfo']>>
>;
export type UtxoInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['utxoInfo']>>
>;
export type TxCborResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['txCbor']>>
>;
export type TxInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['txInfo']>>
>;
export type TxMetadataResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['txMetadata']>>
>;
export type TxMetalabelsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['txMetalabels']>>
>;
export type SubmittxResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['submittx']>>
>;
export type TxStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['txStatus']>>
>;
export type TxUtxosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['txUtxos']>>
>;
export type AddressInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['addressInfo']>>
>;
export type AddressUtxosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['addressUtxos']>>
>;
export type CredentialUtxosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['credentialUtxos']>>
>;
export type AddressTxsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['addressTxs']>>
>;
export type CredentialTxsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['credentialTxs']>>
>;
export type AddressAssetsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['addressAssets']>>
>;
export type AccountListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountList']>>
>;
export type AccountInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountInfo']>>
>;
export type AccountInfoCachedResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountInfoCached']>>
>;
export type AccountUtxosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountUtxos']>>
>;
export type AccountTxsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountTxs']>>
>;
export type AccountRewardsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountRewards']>>
>;
export type AccountUpdatesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountUpdates']>>
>;
export type AccountAddressesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountAddresses']>>
>;
export type AccountAssetsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountAssets']>>
>;
export type AccountHistoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['accountHistory']>>
>;
export type AssetListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetList']>>
>;
export type PolicyAssetListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['policyAssetList']>>
>;
export type AssetTokenRegistryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetTokenRegistry']>>
>;
export type AssetInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetInfo']>>
>;
export type AssetUtxosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetUtxos']>>
>;
export type AssetHistoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetHistory']>>
>;
export type AssetAddressesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetAddresses']>>
>;
export type AssetNftAddressResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetNftAddress']>>
>;
export type PolicyAssetAddressesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['policyAssetAddresses']>>
>;
export type PolicyAssetInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['policyAssetInfo']>>
>;
export type PolicyAssetMintsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['policyAssetMints']>>
>;
export type AssetSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetSummary']>>
>;
export type AssetTxsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['assetTxs']>>
>;
export type DrepEpochSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepEpochSummary']>>
>;
export type DrepListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepList']>>
>;
export type DrepInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepInfo']>>
>;
export type DrepMetadataResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepMetadata']>>
>;
export type DrepUpdatesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepUpdates']>>
>;
export type DrepVotesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepVotes']>>
>;
export type DrepDelegatorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['drepDelegators']>>
>;
export type CommitteeInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['committeeInfo']>>
>;
export type CommitteeVotesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['committeeVotes']>>
>;
export type ProposalListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['proposalList']>>
>;
export type VoterProposalListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['voterProposalList']>>
>;
export type ProposalVotingSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['proposalVotingSummary']>>
>;
export type ProposalVotesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['proposalVotes']>>
>;
export type PoolListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolList']>>
>;
export type PoolInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolInfo']>>
>;
export type PoolStakeSnapshotResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolStakeSnapshot']>>
>;
export type PoolDelegatorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolDelegators']>>
>;
export type PoolDelegatorsHistoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolDelegatorsHistory']>>
>;
export type PoolBlocksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolBlocks']>>
>;
export type PoolHistoryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolHistory']>>
>;
export type PoolUpdatesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolUpdates']>>
>;
export type PoolRegistrationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolRegistrations']>>
>;
export type PoolRetirementsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolRetirements']>>
>;
export type PoolRelaysResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolRelays']>>
>;
export type PoolVotesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolVotes']>>
>;
export type PoolMetadataResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['poolMetadata']>>
>;
export type ScriptInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['scriptInfo']>>
>;
export type NativeScriptListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['nativeScriptList']>>
>;
export type PlutusScriptListResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['plutusScriptList']>>
>;
export type ScriptRedeemersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['scriptRedeemers']>>
>;
export type ScriptUtxosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['scriptUtxos']>>
>;
export type DatumInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['datumInfo']>>
>;
export type OgmiosResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getKoiosAPI>['ogmios']>>
>;
