/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * Base16-encoded 33 byte digest - digest with extra byte with tree height
 */
export type ADDigest = string;
export const bigIntsADDigest: Array<string> = [];
