/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ErgoAddress } from './ergoAddress';

/**
 * Validity status of Ergo address
 */
export interface AddressValidity {
  address: ErgoAddress;
  isValid: boolean;
  error?: string;
}
