/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */
import type { ErgoAddress } from './ergoAddress';

import { bigIntsErgoAddress } from './ergoAddress';

/**
 * Holds encoded ErgoAddress
 */
export interface AddressHolder {
  address: ErgoAddress;
}

export const bigIntsAddressHolder = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`
  ),
];
