/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';

/**
 * Holds encoded ErgoAddress
 */
export interface AddressHolder {
  address: ErgoAddress;
}

export const bigIntsAddressHolder: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`,
  ),
];
