/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */
import type { ErgoAddress } from './ergoAddress';

import { bigIntsErgoAddress } from './ergoAddress';

/**
 * Validity status of Ergo address
 */
export interface AddressValidity {
  address: ErgoAddress;
  isValid: boolean;
  error?: string;
}

export const bigIntsAddressValidity = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`
  ),
];
