/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { AndPredicateAllOf } from './andPredicateAllOf';
import { bigIntsAndPredicateAllOf } from './andPredicateAllOf';
import type { AndPredicateAllOfTwo } from './andPredicateAllOfTwo';
import { bigIntsAndPredicateAllOfTwo } from './andPredicateAllOfTwo';
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';

export type AndPredicate = ScanningPredicate &
  AndPredicateAllOf &
  unknown &
  AndPredicateAllOfTwo;

export const bigIntsAndPredicate: Array<string> = [
  ...bigIntsScanningPredicate,
  ...bigIntsAndPredicateAllOf,
  ...bigIntsAndPredicateAllOfTwo,
];
