/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { Digest32 } from './digest32';

/**
 * Token detail in the transaction
 */
export interface Asset {
  tokenId: Digest32;
  /** Amount of the token */
  amount: bigint;
}
