/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { ErgoAddress } from './ergoAddress';
import type { Registers } from './registers';

/**
 * Request for generation of asset issue transaction
 */
export interface AssetIssueRequest {
  /** Optional, first address in the wallet will be used if not defined */
  address?: ErgoAddress;
  /** Optional, amount of ergs to be put into box with issued assets */
  ergValue?: number;
  /** Supply amount */
  amount: number;
  /** Assets name */
  name: string;
  /** Assets description */
  description: string;
  /** Number of decimal places */
  decimals: number;
  /** Optional, possible values for registers R7...R9 */
  registers?: Registers;
}
