/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';
import type { Registers } from './registers';
import { bigIntsRegisters } from './registers';

/**
 * Request for generation of asset issue transaction
 */
export interface AssetIssueRequest {
  /** Optional, first address in the wallet will be used if not defined */
  address?: ErgoAddress;
  /** Optional, amount of ergs to be put into box with issued assets */
  ergValue?: bigint;
  /** Supply amount */
  amount: bigint;
  /** Assets name */
  name: string;
  /** Assets description */
  description: string;
  /** Number of decimal places */
  decimals: number;
  /** Optional, possible values for registers R7...R9 */
  registers?: Registers;
}

export const bigIntsAssetIssueRequest: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`,
  ),
  'ergValue',
  'amount',
  ...bigIntsRegisters.map((item) =>
    item === '' ? 'registers' : `registers.${item}`,
  ),
];
