/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { Asset } from './asset';
import { bigIntsAsset } from './asset';

/**
 * Amount of Ergo tokens and assets
 */
export interface BalancesSnapshot {
  height: number;
  balance: bigint;
  assets?: Asset[];
}

export const bigIntsBalancesSnapshot: Array<string> = [
  'balance',
  ...bigIntsAsset.map((item) => (item === '' ? 'assets' : `assets.${item}`)),
];
