/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { BalanceInfoTokensItem } from './balanceInfoTokensItem';
import { bigIntsBalanceInfoTokensItem } from './balanceInfoTokensItem';

/**
 * Balance information
 */
export interface BalanceInfo {
  /** Balance of nanoERGs */
  nanoErgs: bigint;
  /** Balance of tokens */
  tokens: BalanceInfoTokensItem[];
}

export const bigIntsBalanceInfo: Array<string> = [
  'nanoErgs',
  ...bigIntsBalanceInfoTokensItem.map((item) =>
    item === '' ? 'tokens' : `tokens.${item}`,
  ),
];
