/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { BalanceInfoTokensItem } from './balanceInfoTokensItem';

/**
 * Balance information
 */
export interface BalanceInfo {
  /** Balance of nanoERGs */
  nanoErgs: number;
  /** Balance of tokens */
  tokens: BalanceInfoTokensItem[];
}
