/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ModifierId } from './modifierId';

export type BalanceInfoTokensItem = {
  /** Identifier of the token */
  tokenId?: ModifierId;
  /** Amount of the token */
  amount?: bigint;
  /** Number of decimals of the token */
  decimals?: bigint;
  /** Name of the token, if any */
  name?: string;
};
