/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

export interface BlacklistedPeers {
  addresses: string[];
}
export const bigIntsBlacklistedPeers: Array<string> = [];
