/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { ModifierId } from './modifierId';
import type { SerializedAdProof } from './serializedAdProof';
import type { Digest32 } from './digest32';

export interface BlockADProofs {
  headerId: ModifierId;
  proofBytes: SerializedAdProof;
  digest: Digest32;
  /** Size in bytes */
  size: bigint;
}
