/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';
import type { SerializedAdProof } from './serializedAdProof';
import { bigIntsSerializedAdProof } from './serializedAdProof';
import type { Digest32 } from './digest32';

import { bigIntsDigest32 } from './digest32';

export interface BlockADProofs {
  headerId: ModifierId;
  proofBytes: SerializedAdProof;
  digest: Digest32;
  /** Size in bytes */
  size: number;
}

export const bigIntsBlockADProofs = [
  ...bigIntsModifierId.map((item) => `headerId.${item}`),
  ...bigIntsSerializedAdProof.map((item) => `proofBytes.${item}`),
  ...bigIntsDigest32.map((item) => `digest.${item}`),
];
