/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { ModifierId } from './modifierId';
import type { Timestamp } from './timestamp';
import type { Version } from './version';
import type { Digest32 } from './digest32';
import type { ADDigest } from './aDDigest';
import type { PowSolutions } from './powSolutions';
import type { Votes } from './votes';

export interface BlockHeader {
  id: ModifierId;
  timestamp: Timestamp;
  version: Version;
  adProofsRoot: Digest32;
  stateRoot: ADDigest;
  transactionsRoot: Digest32;
  nBits: number;
  extensionHash: Digest32;
  powSolutions: PowSolutions;
  height: number;
  difficulty: string;
  parentId: ModifierId;
  votes: Votes;
  /** Size in bytes */
  size?: number;
  extensionId?: ModifierId;
  transactionsId?: ModifierId;
  adProofsId?: ModifierId;
}
