/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { ModifierId } from './modifierId';
import type { Transactions } from './transactions';

export interface BlockTransactions {
  headerId: ModifierId;
  transactions: Transactions;
  /** Size in bytes */
  size: bigint;
}
