/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * Base16-encoded block signature
 */
export type BlockSignature = string;
export const bigIntsBlockSignature: Array<string> = [];
