/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { BoxesRequestHolderTargetAssetsItemItem } from './boxesRequestHolderTargetAssetsItemItem';

import { bigIntsBoxesRequestHolderTargetAssetsItemItem } from './boxesRequestHolderTargetAssetsItemItem';

/**
 * Holds request for wallet boxes
 */
export interface BoxesRequestHolder {
  /** Target assets */
  targetAssets: BoxesRequestHolderTargetAssetsItemItem[][];
  /** Target balance */
  targetBalance: bigint;
}

export const bigIntsBoxesRequestHolder = [
  ...bigIntsBoxesRequestHolderTargetAssetsItemItem.map(
    (item) => `targetAssets.${item}`
  ),
  'targetBalance',
];
