/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * TokenId or Long
 */
export type BoxesRequestHolderTargetAssetsItemItem = string | number;
export const bigIntsBoxesRequestHolderTargetAssetsItemItem: Array<string> = [];
