/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

/**
 * TokenId or Long
 */
export type BoxesRequestHolderTargetAssetsItemItem = string | number;
export const bigIntsBoxesRequestHolderTargetAssetsItemItem = [];
