/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { Asset } from './asset';

import { bigIntsAsset } from './asset';

/**
 * Request for burning tokens in wallet
 */
export interface BurnTokensRequest {
  /** Assets list to burn in the transaction */
  assetsToBurn: Asset[];
}

export const bigIntsBurnTokensRequest: Array<string> = [
  ...bigIntsAsset.map((item) =>
    item === '' ? 'assetsToBurn' : `assetsToBurn.${item}`,
  ),
];
