/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

export interface CheckWallet {
  /** Mnemonic seed (optional) */
  mnemonic: string;
  /** Optional pass to password-protect mnemonic seed */
  mnemonicPass?: string;
}
export const bigIntsCheckWallet = [];
