/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { CommitmentHint } from './commitmentHint';
import { bigIntsCommitmentHint } from './commitmentHint';
import type { CommitmentType } from './commitmentType';
import { bigIntsCommitmentType } from './commitmentType';
import type { SigmaBoolean } from './sigmaBoolean';
import { bigIntsSigmaBoolean } from './sigmaBoolean';

/**
 * basic trait for prover commitments
 */
export interface Commitment {
  hint: CommitmentHint;
  pubkey: SigmaBoolean;
  position: string;
  type?: CommitmentType;
  /** a group element of the commitment */
  a: string;
  /** b group element of the commitment (needed for DHT protocol only) */
  b?: string;
}

export const bigIntsCommitment: Array<string> = [
  ...bigIntsCommitmentHint.map((item) =>
    item === '' ? 'hint' : `hint.${item}`,
  ),
  ...bigIntsSigmaBoolean.map((item) =>
    item === '' ? 'pubkey' : `pubkey.${item}`,
  ),
  ...bigIntsCommitmentType.map((item) =>
    item === '' ? 'type' : `type.${item}`,
  ),
];
