/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

export type CommitmentType =
  (typeof CommitmentType)[keyof typeof CommitmentType];

// eslint-disable-next-line no-redeclare
export const CommitmentType = {
  dlog: 'dlog',
  dht: 'dht',
} as const;
export const bigIntsCommitmentType: Array<string> = [];
