/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { Commitment } from './commitment';

/**
 * commitment to secret along with secret (!) randomness
 */
export type CommitmentWithSecret = Commitment;
