/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { CommitmentHint } from './commitmentHint';
import type { SigmaBoolean } from './sigmaBoolean';
import type { CommitmentType } from './commitmentType';

/**
 * basic trait for prover commitments
 */
export interface Commitment {
  hint: CommitmentHint;
  pubkey: SigmaBoolean;
  position: string;
  type?: CommitmentType;
  /** a group element of the commitment */
  a: string;
  /** b group element of the commitment (needed for DHT protocol only) */
  b?: string;
}
