/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

export type CommitmentHint =
  (typeof CommitmentHint)[keyof typeof CommitmentHint];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommitmentHint = {
  cmtWithSecret: 'cmtWithSecret',
  cmtReal: 'cmtReal',
  cmtSimulated: 'cmtSimulated',
} as const;
export const bigIntsCommitmentHint = [];
