/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { Commitment } from './commitment';
import { bigIntsCommitment } from './commitment';

/**
 * commitment to secret along with secret (!) randomness
 */
export type CommitmentWithSecret = Commitment;
export const bigIntsCommitmentWithSecret: Array<string> = [
  ...bigIntsCommitment,
];
