/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { Timestamp } from './timestamp';

import { bigIntsTimestamp } from './timestamp';

export interface ConnectedPeer {
  address: string;
  version?: string;
  lastMessage?: Timestamp;
}
export const bigIntsConnectedPeer = [
  ...bigIntsTimestamp.map((item) => `lastMessage.${item}`),
];
