/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ConnectedPeer } from './connectedPeer';
import { bigIntsConnectedPeer } from './connectedPeer';

export interface ConnectedPeerByModifierId {
  [key: string]: ConnectedPeer;
}
export const bigIntsConnectedPeerByModifierId: Array<string> = [];
