/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { ContainsPredicateAllOf } from './containsPredicateAllOf';
import { bigIntsContainsPredicateAllOf } from './containsPredicateAllOf';
import type { ContainsPredicateAllOfTwo } from './containsPredicateAllOfTwo';
import { bigIntsContainsPredicateAllOfTwo } from './containsPredicateAllOfTwo';
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';

export type ContainsPredicate = ScanningPredicate &
  ContainsPredicateAllOf &
  unknown &
  ContainsPredicateAllOfTwo;

export const bigIntsContainsPredicate: Array<string> = [
  ...bigIntsScanningPredicate,
  ...bigIntsContainsPredicateAllOf,
  ...bigIntsContainsPredicateAllOfTwo,
];
