/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';
import type { ContainsPredicateAllOf } from './containsPredicateAllOf';
import { bigIntsContainsPredicateAllOf } from './containsPredicateAllOf';
import type { ContainsPredicateAllOfTwo } from './containsPredicateAllOfTwo';

import { bigIntsContainsPredicateAllOfTwo } from './containsPredicateAllOfTwo';

export type ContainsPredicate = ScanningPredicate &
  ContainsPredicateAllOf &
  unknown &
  ContainsPredicateAllOfTwo;

export const bigIntsContainsPredicate = [
  ...bigIntsScanningPredicate,
  ...bigIntsContainsPredicateAllOf,
  ...bigIntsContainsPredicateAllOfTwo,
];
