/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ContainsAssetPredicateAllOf } from './containsAssetPredicateAllOf';
import { bigIntsContainsAssetPredicateAllOf } from './containsAssetPredicateAllOf';
import type { ContainsAssetPredicateAllOfTwo } from './containsAssetPredicateAllOfTwo';
import { bigIntsContainsAssetPredicateAllOfTwo } from './containsAssetPredicateAllOfTwo';
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';

export type ContainsAssetPredicate = ScanningPredicate &
  ContainsAssetPredicateAllOf &
  unknown &
  ContainsAssetPredicateAllOfTwo;

export const bigIntsContainsAssetPredicate: Array<string> = [
  ...bigIntsScanningPredicate,
  ...bigIntsContainsAssetPredicateAllOf,
  ...bigIntsContainsAssetPredicateAllOfTwo,
];
