/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */
import type { ErgoAddress } from './ergoAddress';

import { bigIntsErgoAddress } from './ergoAddress';

export interface DeriveNextKeyResult {
  /** Derivation path of the resulted secret */
  derivationPath: string;
  address: ErgoAddress;
}

export const bigIntsDeriveNextKeyResult = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`
  ),
];
