/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';

export interface DeriveKeyResult {
  address: ErgoAddress;
}

export const bigIntsDeriveKeyResult: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`,
  ),
];
