/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';

export interface DeriveNextKeyResult {
  /** Derivation path of the resulted secret */
  derivationPath: string;
  address: ErgoAddress;
}

export const bigIntsDeriveNextKeyResult: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`,
  ),
];
