/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

/**
 * Base16-encoded 32 byte digest
 */
export type Digest32 = string;
export const bigIntsDigest32 = [];
