/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * Hex-encoded big-endian 256-bits secret exponent
 */
export type DlogSecret = string;
export const bigIntsDlogSecret: Array<string> = [];
