/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

/**
 * Randomness and commitment for the first step of the Schnorr protocol
 */
export interface DlogCommitment {
  /** Hex-encoded big-endian 256-bits secret exponent */
  r: string;
  /** Hex-encoded "g" generator for the Diffie-Hellman tuple (secp256k1 curve point) */
  a: string;
}
