/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

/**
 * Hex-encoded big-endian 256-bits secret exponent
 */
export type DlogSecret = string;
export const bigIntsDlogSecret = [];
