/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

/**
 * Emission info for height
 */
export interface EmissionInfo {
  minerReward?: bigint;
  totalCoinsIssued?: bigint;
  totalRemainCoins?: bigint;
  reemitted?: bigint;
}
