/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';
import type { EqualsPredicateAllOf } from './equalsPredicateAllOf';
import { bigIntsEqualsPredicateAllOf } from './equalsPredicateAllOf';
import type { EqualsPredicateAllOfTwo } from './equalsPredicateAllOfTwo';

import { bigIntsEqualsPredicateAllOfTwo } from './equalsPredicateAllOfTwo';

export type EqualsPredicate = ScanningPredicate &
  EqualsPredicateAllOf &
  unknown &
  EqualsPredicateAllOfTwo;

export const bigIntsEqualsPredicate = [
  ...bigIntsScanningPredicate,
  ...bigIntsEqualsPredicateAllOf,
  ...bigIntsEqualsPredicateAllOfTwo,
];
