/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransactionUnsignedInputExtension } from './ergoTransactionUnsignedInputExtension';
import { bigIntsErgoTransactionUnsignedInputExtension } from './ergoTransactionUnsignedInputExtension';
import type { TransactionBoxId } from './transactionBoxId';
import { bigIntsTransactionBoxId } from './transactionBoxId';

export interface ErgoTransactionUnsignedInput {
  boxId: TransactionBoxId;
  extension?: ErgoTransactionUnsignedInputExtension;
}

export const bigIntsErgoTransactionUnsignedInput: Array<string> = [
  ...bigIntsTransactionBoxId.map((item) =>
    item === '' ? 'boxId' : `boxId.${item}`,
  ),
  ...bigIntsErgoTransactionUnsignedInputExtension.map((item) =>
    item === '' ? 'extension' : `extension.${item}`,
  ),
];
