/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { TransactionId } from './transactionId';
import { bigIntsTransactionId } from './transactionId';
import type { ErgoBoxWithSpendingProof } from './ergoBoxWithSpendingProof';
import { bigIntsErgoBoxWithSpendingProof } from './ergoBoxWithSpendingProof';
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import { bigIntsErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';

import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';

/**
 * Transaction indexed with extra information
 */
export interface ErgoTransactionWithInputBoxes {
  id: TransactionId;
  /** Transaction inputs */
  inputs: ErgoBoxWithSpendingProof[];
  /** Transaction data inputs */
  dataInputs: ErgoTransactionDataInput[];
  /** Transaction outputs */
  outputs: ErgoTransactionOutput[];
  /** Size in bytes */
  size: number;
}

export const bigIntsErgoTransactionWithInputBoxes: Array<string> = [
  ...bigIntsTransactionId.map((item) => (item === '' ? 'id' : `id.${item}`)),
  ...bigIntsErgoBoxWithSpendingProof.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`
  ),
  ...bigIntsErgoTransactionDataInput.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`
  ),
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`
  ),
];
