/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.22
 */
import type { TransactionId } from './transactionId';
import { bigIntsTransactionId } from './transactionId';
import type { ErgoTransactionInput } from './ergoTransactionInput';
import { bigIntsErgoTransactionInput } from './ergoTransactionInput';
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import { bigIntsErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';

import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';

/**
 * ErgoTransaction is an atomic operation which changes UTXO state.
 */
export interface ErgoTransaction {
  /** Id of the transaction */
  id?: TransactionId;
  /** Inputs, that will be spent by this transaction */
  inputs: ErgoTransactionInput[];
  /** Read-only inputs, that are not going to be spent by transaction. */
  dataInputs: ErgoTransactionDataInput[];
  /** Outputs of the transaction, i.e. box candidates to be created by this transaction. */
  outputs: ErgoTransactionOutput[];
  /** Size of ErgoTransaction in bytes */
  size?: number;
}

export const bigIntsErgoTransaction = [
  ...bigIntsTransactionId.map((item) => (item === '' ? 'id' : `id.${item}`)),
  ...bigIntsErgoTransactionInput.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`
  ),
  ...bigIntsErgoTransactionDataInput.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`
  ),
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`
  ),
];
