/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';
import type { ErgoBoxWithSpendingProofAllOf } from './ergoBoxWithSpendingProofAllOf';

import { bigIntsErgoBoxWithSpendingProofAllOf } from './ergoBoxWithSpendingProofAllOf';

export type ErgoBoxWithSpendingProof = ErgoTransactionOutput &
  ErgoBoxWithSpendingProofAllOf;
export const bigIntsErgoBoxWithSpendingProof: Array<string> = [
  ...bigIntsErgoTransactionOutput,
  ...bigIntsErgoBoxWithSpendingProofAllOf,
];
