/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import { bigIntsErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionInput } from './ergoTransactionInput';
import { bigIntsErgoTransactionInput } from './ergoTransactionInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';

export interface ErgoLikeTransaction {
  id: ModifierId;
  inputs: ErgoTransactionInput[];
  dataInputs: ErgoTransactionDataInput[];
  outputs: ErgoTransactionOutput[];
}

export const bigIntsErgoLikeTransaction: Array<string> = [
  ...bigIntsModifierId.map((item) => (item === '' ? 'id' : `id.${item}`)),
  ...bigIntsErgoTransactionInput.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`,
  ),
  ...bigIntsErgoTransactionDataInput.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`,
  ),
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`,
  ),
];
