/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { SpendingProof } from './spendingProof';
import { bigIntsSpendingProof } from './spendingProof';
import type { TransactionBoxId } from './transactionBoxId';

import { bigIntsTransactionBoxId } from './transactionBoxId';

/**
 * Box indexed with extra information
 */
export type ErgoBoxWithSpendingProofAllOf = {
  spendingProof: SpendingProof;
  boxId: TransactionBoxId;
};

export const bigIntsErgoBoxWithSpendingProofAllOf: Array<string> = [
  ...bigIntsSpendingProof.map((item) =>
    item === '' ? 'spendingProof' : `spendingProof.${item}`
  ),
  ...bigIntsTransactionBoxId.map((item) =>
    item === '' ? 'boxId' : `boxId.${item}`
  ),
];
