/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoBoxWithSpendingProofAllOf } from './ergoBoxWithSpendingProofAllOf';
import { bigIntsErgoBoxWithSpendingProofAllOf } from './ergoBoxWithSpendingProofAllOf';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';

export type ErgoBoxWithSpendingProof = ErgoTransactionOutput &
  ErgoBoxWithSpendingProofAllOf;
export const bigIntsErgoBoxWithSpendingProof: Array<string> = [
  ...bigIntsErgoTransactionOutput,
  ...bigIntsErgoBoxWithSpendingProofAllOf,
];
