/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { TransactionBoxId } from './transactionBoxId';
import type { ErgoTransactionUnsignedInputExtension } from './ergoTransactionUnsignedInputExtension';

export interface ErgoTransactionUnsignedInput {
  boxId: TransactionBoxId;
  extension?: ErgoTransactionUnsignedInputExtension;
}
