/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * prover-defined key-value pairs, that may be used inside a script
 */
export type ErgoLikeContextExtension = { [key: string]: unknown };
export const bigIntsErgoLikeContextExtension: Array<string> = [];
