/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * ErgoScript version to be used in compiler
 */
export type ExecuteScriptTreeVersion = unknown | null;
export const bigIntsExecuteScriptTreeVersion: Array<string> = [];
