/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ExecuteScriptNamedConstants } from './executeScriptNamedConstants';
import { bigIntsExecuteScriptNamedConstants } from './executeScriptNamedConstants';
import type { ErgoLikeContext } from './ergoLikeContext';

import { bigIntsErgoLikeContext } from './ergoLikeContext';

export interface ExecuteScript {
  /** Sigma script to be executed */
  script: string;
  /** Environment for compiler */
  namedConstants: ExecuteScriptNamedConstants;
  /** Interpreter context */
  context: ErgoLikeContext;
}

export const bigIntsExecuteScript = [
  ...bigIntsExecuteScriptNamedConstants.map((item) =>
    item === '' ? 'namedConstants' : `namedConstants.${item}`
  ),
  ...bigIntsErgoLikeContext.map((item) =>
    item === '' ? 'context' : `context.${item}`
  ),
];
