/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { FeeHistogramBin } from './feeHistogramBin';

import { bigIntsFeeHistogramBin } from './feeHistogramBin';

/**
 * Fee histogram for transactions in mempool
 */
export type FeeHistogram = FeeHistogramBin[];
export const bigIntsFeeHistogram = [...bigIntsFeeHistogramBin];
