/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { DlogSecret } from './dlogSecret';
import type { DhtSecret } from './dhtSecret';

/**
 * Optionally, external secrets used for signing
 */
export type GenerateCommitmentsRequestSecrets = {
  /** Sequence of secret exponents (DLOG secrets) */
  dlog?: DlogSecret[];
  /** Sequence of secret Diffie-Hellman tuple exponents (DHT secrets) */
  dht?: DhtSecret[];
};
