/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { DhtSecret } from './dhtSecret';
import { bigIntsDhtSecret } from './dhtSecret';
import type { DlogSecret } from './dlogSecret';
import { bigIntsDlogSecret } from './dlogSecret';

/**
 * Optionally, external secrets used for signing
 */
export type GenerateCommitmentsRequestSecrets = {
  /** Sequence of secret exponents (DLOG secrets) */
  dlog?: DlogSecret[];
  /** Sequence of secret Diffie-Hellman tuple exponents (DHT secrets) */
  dht?: DhtSecret[];
};

export const bigIntsGenerateCommitmentsRequestSecrets: Array<string> = [
  ...bigIntsDlogSecret.map((item) => (item === '' ? 'dlog' : `dlog.${item}`)),
  ...bigIntsDhtSecret.map((item) => (item === '' ? 'dht' : `dht.${item}`)),
];
