/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { DlogSecret } from './dlogSecret';
import { bigIntsDlogSecret } from './dlogSecret';
import type { DhtSecret } from './dhtSecret';

import { bigIntsDhtSecret } from './dhtSecret';

/**
 * Optionally, external secrets used for signing
 */
export type GenerateCommitmentsRequestSecrets = {
  /** Sequence of secret exponents (DLOG secrets) */
  dlog?: DlogSecret[];
  /** Sequence of secret Diffie-Hellman tuple exponents (DHT secrets) */
  dht?: DhtSecret[];
};

export const bigIntsGenerateCommitmentsRequestSecrets = [
  ...bigIntsDlogSecret.map((item) => `dlog.${item}`),
  ...bigIntsDhtSecret.map((item) => `dht.${item}`),
];
