/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

export type GetBoxesByAddressUnspentParams = {
  /**
   * amount of elements to skip from the start
   */
  offset?: bigint;
  /**
   * amount of elements to retrieve
   */
  limit?: bigint;
  /**
   * desc = new boxes first ; asc = old boxes first
   */
  sortDirection?: string;
};
