/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

export type GetBoxRangeParams = {
  /**
   * amount of elements to skip from the start
   */
  offset?: number;
  /**
   * amount of elements to retrieve
   */
  limit?: number;
};
export const bigIntsGetBoxRangeParams: Array<string> = [];
