/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type GetBoxesByErgoTreeUnspentParams = {
  /**
   * amount of elements to skip from the start
   */
  offset?: number;
  /**
   * amount of elements to retrieve
   */
  limit?: number;
  /**
   * desc = new boxes first ; asc = old boxes first
   */
  sortDirection?: string;
  /**
   * if true include unconfirmed transactions from mempool
   */
  includeUnconfirmed?: boolean;
  /**
   * if true exclude spent inputs from mempool
   */
  excludeMempoolSpent?: boolean;
};
export const bigIntsGetBoxesByErgoTreeUnspentParams: Array<string> = [];
