/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

export type GetChainSliceParams = {
  /**
   * Min header height
   */
  fromHeight?: bigint;
  /**
   * Max header height (best header height by default)
   */
  toHeight?: bigint;
};
