/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

export type GetExpectedWaitTimeParams = {
  /**
   * Transaction fee (in nanoErgs)
   * @minimum 1
   */
  fee?: number;
  /**
   * Transaction size
   * @minimum 1
   */
  txSize?: number;
};
export const bigIntsGetExpectedWaitTimeParams: Array<string> = [];
