/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export type GetFeeHistogramParams = {
  /**
   * The number of bins in histogram
   */
  bins?: number;
  /**
   * Maximal wait time in milliseconds
   */
  maxtime?: number;
};
