/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */

export type GetHeaderIdsParams = {
  /**
   * The number of items in list to return
   */
  limit?: number;
  /**
   * The first block height to include in the list
   */
  offset?: number;
};
export const bigIntsGetHeaderIdsParams = [];
