/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type GetIndexedHeight200 = {
  /** number of blocks indexed */
  indexedHeight?: number;
  /** number of all known blocks */
  fullHeight?: number;
};
export const bigIntsGetIndexedHeight200: Array<string> = [];
