/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export type GetIndexedHeight200 = {
  /** number of blocks indexed */
  indexedHeight?: number;
  /** number of all known blocks */
  fullHeight?: number;
};
