/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export type GetRecommendedFeeParams = {
  /**
   * Maximum transaction wait time in minutes
   */
  waitTime?: number;
  /**
   * Transaction size
   */
  txSize?: number;
};
