/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { IndexedErgoTransaction } from './indexedErgoTransaction';

import { bigIntsIndexedErgoTransaction } from './indexedErgoTransaction';

export type GetTxsByAddress200 = {
  /** Array of transactions */
  items?: IndexedErgoTransaction[];
  /** Total count of retreived transactions */
  total?: number;
};
export const bigIntsGetTxsByAddress200 = [
  ...bigIntsIndexedErgoTransaction.map((item) => `items.${item}`),
];
