/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { IndexedErgoTransaction } from './indexedErgoTransaction';
import { bigIntsIndexedErgoTransaction } from './indexedErgoTransaction';

export type GetTxsByAddress200 = {
  /** Array of transactions */
  items?: IndexedErgoTransaction[];
  /** Total count of retrieved transactions */
  total?: number;
};

export const bigIntsGetTxsByAddress200: Array<string> = [
  ...bigIntsIndexedErgoTransaction.map((item) =>
    item === '' ? 'items' : `items.${item}`,
  ),
];
