/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export type GetUnconfirmedTransactionsParams = {
  /**
   * The number of items in list to return
   */
  limit?: number;
  /**
   * The number of items in list to skip
   */
  offset?: number;
};
