/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type GetUnconfirmedTransactionOutputBoxesByErgoTreeParams = {
  /**
   * The number of items in list to return
   */
  limit?: number;
  /**
   * The number of items in list to skip
   */
  offset?: number;
};
export const bigIntsGetUnconfirmedTransactionOutputBoxesByErgoTreeParams: Array<string> =
  [];
