/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { TransactionId } from './transactionId';
import type { ErgoTransactionInput } from './ergoTransactionInput';
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import type { ModifierId } from './modifierId';
import type { Timestamp } from './timestamp';

/**
 * Transaction indexed with extra information
 */
export interface IndexedErgoTransaction {
  id: TransactionId;
  /** Transaction inputs */
  inputs: ErgoTransactionInput[];
  /** Transaction data inputs */
  dataInputs: ErgoTransactionDataInput[];
  /** Transaction outputs */
  outputs: ErgoTransactionOutput[];
  /** Height of a block the transaction was included in */
  inclusionHeight: bigint;
  /** Number of transaction confirmations */
  numConfirmations: bigint;
  /** Id of the block the transaction was included in */
  blockId: ModifierId;
  timestamp: Timestamp;
  /** index of the transaction in the block it was included in */
  index: bigint;
  /** Global index of the transaction in the blockchain */
  globalIndex: bigint;
  /** Size in bytes */
  size: bigint;
}
