/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';
import type { SpendingProof } from './spendingProof';
import { bigIntsSpendingProof } from './spendingProof';

/**
 * Box indexed with extra information
 */
export type IndexedErgoBoxAllOf = {
  address: ErgoAddress;
  /**
   * Transaction which spent the box
   * @nullable
   */
  spentTransactionId: ModifierId;
  /**
   * The height the box was spent at
   * @minimum 0
   * @nullable
   */
  spendingHeight: number | null;
  /**
   * The height the transaction containing the box was included in a block at
   * @minimum 0
   */
  inclusionHeight: number;
  /** @nullable */
  spendingProof?: SpendingProof;
  /**
   * Global index of the output in the blockchain
   * @minimum 0
   */
  globalIndex: bigint;
};

export const bigIntsIndexedErgoBoxAllOf: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`,
  ),
  ...bigIntsModifierId.map((item) =>
    item === '' ? 'spentTransactionId' : `spentTransactionId.${item}`,
  ),
  ...bigIntsSpendingProof.map((item) =>
    item === '' ? 'spendingProof' : `spendingProof.${item}`,
  ),
  'globalIndex',
];
