/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { IndexedErgoTransaction } from './indexedErgoTransaction';
import { bigIntsIndexedErgoTransaction } from './indexedErgoTransaction';

/**
 * List of IndexedErgoTransaction objects
 */
export type IndexedTransactions = IndexedErgoTransaction[];
export const bigIntsIndexedTransactions: Array<string> = [
  ...bigIntsIndexedErgoTransaction,
];
