/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';
import type { IndexedTransactions } from './indexedTransactions';

import { bigIntsIndexedTransactions } from './indexedTransactions';

/**
 * Section of a block which contains indexed transactions.
 */
export interface IndexedBlockTransactions {
  /** Identifier of a header of a corresponding block */
  headerId: ModifierId;
  /** IndexedTransactions of the block */
  transactions: IndexedTransactions;
  /** Size in bytes of all block transactions */
  size: number;
}

export const bigIntsIndexedBlockTransactions: Array<string> = [
  ...bigIntsModifierId.map((item) =>
    item === '' ? 'headerId' : `headerId.${item}`,
  ),
  ...bigIntsIndexedTransactions.map((item) =>
    item === '' ? 'transactions' : `transactions.${item}`,
  ),
];
