/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';

/**
 * Token indexed with extra information
 */
export interface IndexedToken {
  /** Id of the token */
  id: ModifierId;
  /** Id of the box that created the token */
  boxId: ModifierId;
  /**
   * The total supply of the token
   * @minimum 1
   */
  emissionAmount: bigint;
  /** The name of the token */
  name: string;
  /** The description of the token */
  description: string;
  /**
   * The number of decimals the token supports
   * @minimum 0
   */
  decimals: number;
}

export const bigIntsIndexedToken: Array<string> = [
  ...bigIntsModifierId.map((item) => (item === '' ? 'id' : `id.${item}`)),
  ...bigIntsModifierId.map((item) => (item === '' ? 'boxId' : `boxId.${item}`)),
  'emissionAmount',
];
