/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ModifierId } from './modifierId';

import { bigIntsModifierId } from './modifierId';

/**
 * Token indexed with extra information
 */
export interface IndexedToken {
  /** Id of the token */
  id?: ModifierId;
  /** Id of the box that created the token */
  boxId?: ModifierId;
  /** The total supply of the token */
  emissionAmount?: bigint;
  /** The name of the token */
  name?: string;
  /** The description of the token */
  description?: string;
  /** The number of decimals the token supports */
  decimals?: number;
}

export const bigIntsIndexedToken = [
  ...bigIntsModifierId.map((item) => `id.${item}`),
  ...bigIntsModifierId.map((item) => `boxId.${item}`),
  'emissionAmount',
];
