/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';
import type { IndexedErgoBoxAllOf } from './indexedErgoBoxAllOf';
import { bigIntsIndexedErgoBoxAllOf } from './indexedErgoBoxAllOf';

export type IndexedErgoBox = ErgoTransactionOutput & IndexedErgoBoxAllOf;
export const bigIntsIndexedErgoBox: Array<string> = [
  ...bigIntsErgoTransactionOutput,
  ...bigIntsIndexedErgoBoxAllOf,
];
