/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */

export interface InitWalletResult {
  /** Mnemonic seed phrase */
  mnemonic: string;
}
export const bigIntsInitWalletResult = [];
