/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export interface InitWallet {
  /** Password to encrypt wallet file with */
  pass: string;
  /** Optional pass to password-protect mnemonic seed */
  mnemonicPass?: string;
}
export const bigIntsInitWallet: Array<string> = [];
