/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export interface InitWallet {
  /** Password to encrypt wallet file with */
  pass: string;
  /** Optional pass to password-protect mnemonic seed */
  mnemonicPass?: string;
}
