/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { Commitment } from './commitment';
import { bigIntsCommitment } from './commitment';
import type { CommitmentWithSecret } from './commitmentWithSecret';
import { bigIntsCommitmentWithSecret } from './commitmentWithSecret';
import type { SecretProven } from './secretProven';
import { bigIntsSecretProven } from './secretProven';

export type InputHintsItem = CommitmentWithSecret | Commitment | SecretProven;

export const bigIntsInputHintsItem: Array<string> = [
  ...bigIntsCommitmentWithSecret,
  ...bigIntsCommitment,
  ...bigIntsSecretProven,
];
