/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { CommitmentWithSecret } from './commitmentWithSecret';
import { bigIntsCommitmentWithSecret } from './commitmentWithSecret';
import type { Commitment } from './commitment';
import { bigIntsCommitment } from './commitment';
import type { SecretProven } from './secretProven';

import { bigIntsSecretProven } from './secretProven';

export type InputHintsItem = CommitmentWithSecret | Commitment | SecretProven;
export const bigIntsInputHintsItem = [];
