/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { HexString } from './hexString';

import { bigIntsHexString } from './hexString';

/**
 * Key-value record represented as a pair of hex strings in an array.
 */
export type KeyValueItem = HexString[];
export const bigIntsKeyValueItem: Array<string> = [...bigIntsHexString];
