/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { HexString } from './hexString';

import { bigIntsHexString } from './hexString';

export type KeyValueItem = HexString[];
export const bigIntsKeyValueItem = [...bigIntsHexString];
