/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type ListSpentScansParams = {
  /**
   * Minimal number of confirmations, -1 means we consider unconfirmed
   */
  minConfirmations?: number;
  /**
   * Maximum number of confirmations, -1 means unlimited
   */
  maxConfirmations?: number;
  /**
   * Minimal box inclusion height
   */
  minInclusionHeight?: number;
  /**
   * Maximum box inclusion height, -1 means unlimited
   */
  maxInclusionHeight?: number;
  /**
   * amount of elements to retrieve
   */
  limit?: number;
  /**
   * The number of items in list to skip
   */
  offset?: number;
};
export const bigIntsListSpentScansParams: Array<string> = [];
