/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

export type ListSpentScansParams = {
  /**
   * Minimal number of confirmations, -1 means we consider unconfirmed
   */
  minConfirmations?: bigint;
  /**
   * Maximum number of confirmations, -1 means unlimited
   */
  maxConfirmations?: bigint;
  /**
   * Minimal box inclusion height
   */
  minInclusionHeight?: bigint;
  /**
   * Maximum box inclusion height, -1 means unlimited
   */
  maxInclusionHeight?: bigint;
};
