/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { MerkleProofLevelsItemItem } from './merkleProofLevelsItemItem';

/**
 * Merkle proof for a leaf, which is an array of bytes (e.g. a transaction identifier)
 */
export interface MerkleProof {
  /** Base16-encoded Merkle tree leaf bytes */
  leaf: string;
  levels: MerkleProofLevelsItemItem[][];
}
