/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransaction } from './ergoTransaction';
import { bigIntsErgoTransaction } from './ergoTransaction';

/**
 * Request to generate a block candidate with transactions and custom miner public key
 */
export interface MiningRequest {
  /** Transactions to include in the block candidate */
  txs: ErgoTransaction[];
  /** Hexadecimal representation of public key to use as minerPk */
  pk: string;
}
export const bigIntsMiningRequest: Array<string> = [
  ...bigIntsErgoTransaction.map((item) =>
    item === '' ? 'txs' : `txs.${item}`,
  ),
];
