/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

/**
 * Base16-encoded 32 byte modifier id
 */
export type ModifierId = string;
export const bigIntsModifierId: Array<string> = [];
