/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { PopowHeader } from './popowHeader';
import { bigIntsPopowHeader } from './popowHeader';
import type { BlockHeader } from './blockHeader';

import { bigIntsBlockHeader } from './blockHeader';

export interface NipopowProof {
  /** security parameter (min μ-level superchain length) */
  m: number;
  /** security parameter (min suffix length, >= 1) */
  k: number;
  /** proof prefix headers */
  prefix: PopowHeader[];
  suffixHead: PopowHeader;
  /** tail of the proof suffix headers */
  suffixTail: BlockHeader[];
}

export const bigIntsNipopowProof: Array<string> = [
  ...bigIntsPopowHeader.map((item) =>
    item === '' ? 'prefix' : `prefix.${item}`
  ),
  ...bigIntsPopowHeader.map((item) =>
    item === '' ? 'suffixHead' : `suffixHead.${item}`
  ),
  ...bigIntsBlockHeader.map((item) =>
    item === '' ? 'suffixTail' : `suffixTail.${item}`
  ),
];
