/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { PopowHeader } from './popowHeader';
import type { BlockHeader } from './blockHeader';

export interface NipopowProof {
  /** security parameter (min μ-level superchain length) */
  m: number;
  /** security parameter (min suffix length, >= 1) */
  k: number;
  /** proof prefix headers */
  prefix: PopowHeader[];
  suffixHead: PopowHeader;
  /** tail of the proof suffix headers */
  suffixTail: BlockHeader[];
}
