/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */

/**
 * Whether the node is storing UTXO set or only its digest. Equals `digest` if only digest is stored, `utxo` if full UTXO set is stored.
 */
export type NodeInfoStateType =
  (typeof NodeInfoStateType)[keyof typeof NodeInfoStateType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeInfoStateType = {
  digest: 'digest',
  utxo: 'utxo',
} as const;
export const bigIntsNodeInfoStateType = [];
