/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.21
 */
import type { NodeInfoStateType } from './nodeInfoStateType';
import { bigIntsNodeInfoStateType } from './nodeInfoStateType';
import type { Parameters } from './parameters';

import { bigIntsParameters } from './parameters';

/**
 * Data container for /info API request output. Contains information about node's state and configuration. Contains data about best block, best header, state, etc. Best block is the block with the maximum height.
 */
export interface NodeInfo {
  /** Node's (peer) self-chosen name from config */
  name: string;
  /** Node's application version */
  appVersion: string;
  /** Height of the best block known to the node. Can be 'null' if state is empty (no full block is applied since node launch) */
  fullHeight: number | null;
  /** The height of the best header (i.e. the one with the maximum height). Can be 'null' if state is empty (no header applied since node launch) */
  headersHeight: number | null;
  /** Maximum block height of connected peers. Can be 'null' if state is empty (no peer connected since node launch) */
  maxPeerHeight: number | null;
  /** Best full-block id (header id of such block). Can be 'null' if no full block is applied since node launch. */
  bestFullHeaderId: string | null;
  /** Header id of the parent block of the best full-block (i.e. previous block in the blockchain). Can be 'null' if no full block is applied since node launch */
  previousFullHeaderId: string | null;
  /** Best header ID (hex representation). Can be 'null' if no header applied since node launch. */
  bestHeaderId: string | null;
  /** Current UTXO set digest. Can be 'null' if state is empty (no full block is applied since node launch) */
  stateRoot: string | null;
  /** Whether the node is storing UTXO set or only its digest. Equals `digest` if only digest is stored, `utxo` if full UTXO set is stored. */
  stateType: NodeInfoStateType;
  /** Id of a block where UTXO set digest is taken from. Can be 'null' if no full block is applied since node launch. */
  stateVersion: string | null;
  /** Whether the node is mining (i.e. generating blocks). */
  isMining: boolean;
  /** Number of peers this node is connected with. */
  peersCount: number;
  /** Number of unconfirmed transactions in the mempool. */
  unconfirmedCount: number;
  /** Difficulty on current bestFullHeaderId. Can be 'null' if no full block is applied since node launch. Difficulty is a BigInt integer. */
  difficulty: number | null;
  /** Current internal node time */
  currentTime: number;
  /** When the node was launched (in Java time format, UNIX time * 1000). */
  launchTime: number;
  /** Cumulative difficulty of best headers-chain. Can be 'null' if no headers is applied since node launch. headersScore is a BigInt integer. */
  headersScore: number | null;
  /** Cumulative difficulty of best full blocks chain. Can be 'null' if no full block is applied since node launch. fullBlocksScore is a BigInt integer. */
  fullBlocksScore: number | null;
  /** Header id of genesis block. Can be 'null' if genesis blocks is not produced yet. */
  genesisBlockId: string | null;
  /** System parameters which could be readjusted via collective miners decision. */
  parameters: Parameters;
  /** Whether EIP-27 locked in */
  eip27Supported?: boolean;
  /** Publicly accessible url of node which exposes restApi in firewall */
  restApiUrl?: string;
}

export const bigIntsNodeInfo = [
  ...bigIntsNodeInfoStateType.map((item) =>
    item === '' ? 'stateType' : `stateType.${item}`
  ),
  ...bigIntsParameters.map((item) =>
    item === '' ? 'parameters' : `parameters.${item}`
  ),
];
