/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { OrPredicateAllOf } from './orPredicateAllOf';
import { bigIntsOrPredicateAllOf } from './orPredicateAllOf';
import type { OrPredicateAllOfTwo } from './orPredicateAllOfTwo';
import { bigIntsOrPredicateAllOfTwo } from './orPredicateAllOfTwo';
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';

export type OrPredicate = ScanningPredicate &
  OrPredicateAllOf &
  unknown &
  OrPredicateAllOfTwo;

export const bigIntsOrPredicate: Array<string> = [
  ...bigIntsScanningPredicate,
  ...bigIntsOrPredicateAllOf,
  ...bigIntsOrPredicateAllOfTwo,
];
