/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { Version } from './version';
import { bigIntsVersion } from './version';

/**
 * System parameters which could be readjusted via collective miners decision.
 */
export interface Parameters {
  /**
   * Height when current parameters were considered(not actual height). Can be '0' if state is empty
   * @minimum 0
   */
  height: number;
  /**
   * Storage fee coefficient (per byte per storage period ~4 years)
   * @minimum 0
   */
  storageFeeFactor: number;
  /**
   * Minimum value per byte of an output
   * @minimum 0
   */
  minValuePerByte: number;
  /**
   * Maximum block size (in bytes)
   * @minimum 0
   */
  maxBlockSize: number;
  /**
   * Maximum cumulative computational cost of input scripts in block transactions
   * @minimum 0
   */
  maxBlockCost: number;
  /** */
  blockVersion: Version;
  /**
   * Validation cost of a single token
   * @minimum 0
   */
  tokenAccessCost: number;
  /**
   * Validation cost per one transaction input
   * @minimum 0
   */
  inputCost: number;
  /**
   * Validation cost per one data input
   * @minimum 0
   */
  dataInputCost: number;
  /**
   * Validation cost per one transaction output
   * @minimum 0
   */
  outputCost: number;
}

export const bigIntsParameters: Array<string> = [
  ...bigIntsVersion.map((item) =>
    item === '' ? 'blockVersion' : `blockVersion.${item}`,
  ),
];
