/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export interface PassphraseMatch {
  /** true if passphrase matches wallet, false otherwise */
  matched: boolean;
}
export const bigIntsPassphraseMatch: Array<string> = [];
