/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';
import type { Asset } from './asset';
import { bigIntsAsset } from './asset';
import type { Registers } from './registers';

import { bigIntsRegisters } from './registers';

/**
 * Request for generation of payment transaction to a given address
 */
export interface PaymentRequest {
  address: ErgoAddress;
  /** Payment amount */
  value: bigint;
  /** Assets list in the transaction */
  assets?: Asset[];
  registers?: Registers;
}

export const bigIntsPaymentRequest: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`
  ),
  'value',
  ...bigIntsAsset.map((item) => (item === '' ? 'assets' : `assets.${item}`)),
  ...bigIntsRegisters.map((item) =>
    item === '' ? 'registers' : `registers.${item}`
  ),
];
