/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { Timestamp } from './timestamp';
import { bigIntsTimestamp } from './timestamp';
import type { PeerConnectionType } from './peerConnectionType';

import { bigIntsPeerConnectionType } from './peerConnectionType';

export interface Peer {
  address: string;
  restApiUrl?: string | null;
  name?: string | null;
  lastSeen?: Timestamp;
  connectionType?: PeerConnectionType;
}

export const bigIntsPeer = [
  ...bigIntsTimestamp.map((item) =>
    item === '' ? 'lastSeen' : `lastSeen.${item}`
  ),
  ...bigIntsPeerConnectionType.map((item) =>
    item === '' ? 'connectionType' : `connectionType.${item}`
  ),
];
