/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type PeerConnectionType =
  (typeof PeerConnectionType)[keyof typeof PeerConnectionType];

// eslint-disable-next-line no-redeclare
export const PeerConnectionType = {
  Incoming: 'Incoming',
  Outgoing: 'Outgoing',
  null: null,
} as const;
export const bigIntsPeerConnectionType: Array<string> = [];
