/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.22
 */

export interface PeerMode {
  state: string;
  verifyingTransactions: boolean;
  fullBlocksSuffix: number;
}
export const bigIntsPeerMode = [];
