/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

export type PeerConnectionType =
  (typeof PeerConnectionType)[keyof typeof PeerConnectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PeerConnectionType = {
  Incoming: 'Incoming',
  Outgoing: 'Outgoing',
  null: null,
} as const;
