/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { BlockHeader } from './blockHeader';
import { bigIntsBlockHeader } from './blockHeader';
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';

export interface PopowHeader {
  header: BlockHeader;
  /** Array of header interlinks */
  interlinks: ModifierId[];
}

export const bigIntsPopowHeader: Array<string> = [
  ...bigIntsBlockHeader.map((item) =>
    item === '' ? 'header' : `header.${item}`,
  ),
  ...bigIntsModifierId.map((item) =>
    item === '' ? 'interlinks' : `interlinks.${item}`,
  ),
];
