/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */

/**
 * An object containing all components of pow solution
 */
export interface PowSolutions {
  /** Base16-encoded public key */
  pk: string;
  w: string;
  n: string;
  d: bigint;
}
