/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { SValue } from './sValue';

import { bigIntsSValue } from './sValue';

/**
 * Ergo box registers
 */
export interface Registers {
  [key: string]: SValue;
}
export const bigIntsRegisters = [];
