/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { PaymentRequest } from './paymentRequest';
import { bigIntsPaymentRequest } from './paymentRequest';
import type { BurnTokensRequest } from './burnTokensRequest';
import { bigIntsBurnTokensRequest } from './burnTokensRequest';
import type { AssetIssueRequest } from './assetIssueRequest';

import { bigIntsAssetIssueRequest } from './assetIssueRequest';

export type RequestsHolderRequestsItem =
  | PaymentRequest
  | BurnTokensRequest
  | AssetIssueRequest;
export const bigIntsRequestsHolderRequestsItem = [];
