/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.22
 */
import type { ErgoAddress } from './ergoAddress';

import { bigIntsErgoAddress } from './ergoAddress';

export interface RewardAddress {
  rewardAddress: ErgoAddress;
}

export const bigIntsRewardAddress = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'rewardAddress' : `rewardAddress.${item}`
  ),
];
