/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';

/**
 * Ergo box with associated scans (their respective identifiers)
 */
export interface ScanIdsBox {
  scanIds: number[];
  box: ErgoTransactionOutput;
}

export const bigIntsScanIdsBox: Array<string> = [
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'box' : `box.${item}`,
  ),
];
