/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { ErgoTransactionOutput } from './ergoTransactionOutput';

/**
 * Ergo box with associated scans (their respective identifiers)
 */
export interface ScanIdsBox {
  scanIds: number[];
  box: ErgoTransactionOutput;
}
