/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type ScanWalletInteraction =
  (typeof ScanWalletInteraction)[keyof typeof ScanWalletInteraction];

// eslint-disable-next-line no-redeclare
export const ScanWalletInteraction = {
  off: 'off',
  shared: 'shared',
  forced: 'forced',
} as const;
export const bigIntsScanWalletInteraction: Array<string> = [];
