/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ScanWalletInteraction } from './scanWalletInteraction';
import { bigIntsScanWalletInteraction } from './scanWalletInteraction';
import type { ScanningPredicate } from './scanningPredicate';

import { bigIntsScanningPredicate } from './scanningPredicate';

export interface Scan {
  scanName?: string;
  scanId?: number;
  walletInteraction?: ScanWalletInteraction;
  removeOffchain?: boolean;
  trackingRule?: ScanningPredicate;
}

export const bigIntsScan = [
  ...bigIntsScanWalletInteraction.map((item) =>
    item === '' ? 'walletInteraction' : `walletInteraction.${item}`
  ),
  ...bigIntsScanningPredicate.map((item) =>
    item === '' ? 'trackingRule' : `trackingRule.${item}`
  ),
];
