/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ScanningPredicate } from './scanningPredicate';
import { bigIntsScanningPredicate } from './scanningPredicate';
import type { ScanRequestWalletInteraction } from './scanRequestWalletInteraction';
import { bigIntsScanRequestWalletInteraction } from './scanRequestWalletInteraction';

export interface ScanRequest {
  scanName?: string;
  removeOffchain?: boolean;
  walletInteraction?: ScanRequestWalletInteraction;
  trackingRule?: ScanningPredicate;
}

export const bigIntsScanRequest: Array<string> = [
  ...bigIntsScanRequestWalletInteraction.map((item) =>
    item === '' ? 'walletInteraction' : `walletInteraction.${item}`,
  ),
  ...bigIntsScanningPredicate.map((item) =>
    item === '' ? 'trackingRule' : `trackingRule.${item}`,
  ),
];
