/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { TransactionBoxId } from './transactionBoxId';

import { bigIntsTransactionBoxId } from './transactionBoxId';

export interface ScanIdBoxId {
  scanId: number;
  boxId: TransactionBoxId;
}

export const bigIntsScanIdBoxId = [
  ...bigIntsTransactionBoxId.map((item) =>
    item === '' ? 'boxId' : `boxId.${item}`
  ),
];
