/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.22
 */

export type ScanWalletInteraction =
  (typeof ScanWalletInteraction)[keyof typeof ScanWalletInteraction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScanWalletInteraction = {
  off: 'off',
  shared: 'shared',
  forced: 'forced',
} as const;
export const bigIntsScanWalletInteraction = [];
