/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export type SecretProvenHint =
  (typeof SecretProvenHint)[keyof typeof SecretProvenHint];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SecretProvenHint = {
  proofReal: 'proofReal',
  proofSimulated: 'proofSimulated',
} as const;
