/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

export type SecretProvenHint =
  (typeof SecretProvenHint)[keyof typeof SecretProvenHint];

// eslint-disable-next-line no-redeclare
export const SecretProvenHint = {
  proofReal: 'proofReal',
  proofSimulated: 'proofSimulated',
} as const;
export const bigIntsSecretProvenHint: Array<string> = [];
