/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { HexString } from './hexString';
import { bigIntsHexString } from './hexString';
import type { TransactionBoxId } from './transactionBoxId';
import { bigIntsTransactionBoxId } from './transactionBoxId';

export interface SerializedBox {
  boxId: TransactionBoxId;
  bytes: HexString;
}

export const bigIntsSerializedBox: Array<string> = [
  ...bigIntsTransactionBoxId.map((item) =>
    item === '' ? 'boxId' : `boxId.${item}`,
  ),
  ...bigIntsHexString.map((item) => (item === '' ? 'bytes' : `bytes.${item}`)),
];
