/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { TransactionBoxId } from './transactionBoxId';
import { bigIntsTransactionBoxId } from './transactionBoxId';
import type { HexString } from './hexString';

import { bigIntsHexString } from './hexString';

export interface SerializedBox {
  boxId: TransactionBoxId;
  bytes: HexString;
}

export const bigIntsSerializedBox = [
  ...bigIntsTransactionBoxId.map((item) => `boxId.${item}`),
  ...bigIntsHexString.map((item) => `bytes.${item}`),
];
