/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { SigmaBoolean } from './sigmaBoolean';
import type { SigmaBooleanAndPredicateAllOf } from './sigmaBooleanAndPredicateAllOf';
import type { SigmaBooleanAndPredicateAllOfTwo } from './sigmaBooleanAndPredicateAllOfTwo';

export type SigmaBooleanAndPredicate = SigmaBoolean &
  SigmaBooleanAndPredicateAllOf &
  unknown &
  SigmaBooleanAndPredicateAllOfTwo;
