/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { SigmaBoolean } from './sigmaBoolean';

import { bigIntsSigmaBoolean } from './sigmaBoolean';

export type SigmaBooleanAndPredicateAllOfTwo = {
  args?: SigmaBoolean[];
};
export const bigIntsSigmaBooleanAndPredicateAllOfTwo: Array<string> = [
  ...bigIntsSigmaBoolean.map((item) => (item === '' ? 'args' : `args.${item}`)),
];
