/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { SigmaBoolean } from './sigmaBoolean';
import { bigIntsSigmaBoolean } from './sigmaBoolean';
import type { SigmaBooleanAndPredicateAllOf } from './sigmaBooleanAndPredicateAllOf';
import { bigIntsSigmaBooleanAndPredicateAllOf } from './sigmaBooleanAndPredicateAllOf';
import type { SigmaBooleanAndPredicateAllOfTwo } from './sigmaBooleanAndPredicateAllOfTwo';
import { bigIntsSigmaBooleanAndPredicateAllOfTwo } from './sigmaBooleanAndPredicateAllOfTwo';

export type SigmaBooleanAndPredicate = SigmaBoolean &
  SigmaBooleanAndPredicateAllOf &
  unknown &
  SigmaBooleanAndPredicateAllOfTwo;

export const bigIntsSigmaBooleanAndPredicate: Array<string> = [
  ...bigIntsSigmaBoolean,
  ...bigIntsSigmaBooleanAndPredicateAllOf,
  ...bigIntsSigmaBooleanAndPredicateAllOfTwo,
];
