/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { SigmaBoolean } from './sigmaBoolean';
import { bigIntsSigmaBoolean } from './sigmaBoolean';
import type { SigmaBooleanOrPredicateAllOf } from './sigmaBooleanOrPredicateAllOf';
import { bigIntsSigmaBooleanOrPredicateAllOf } from './sigmaBooleanOrPredicateAllOf';
import type { SigmaBooleanOrPredicateAllOfTwo } from './sigmaBooleanOrPredicateAllOfTwo';
import { bigIntsSigmaBooleanOrPredicateAllOfTwo } from './sigmaBooleanOrPredicateAllOfTwo';

export type SigmaBooleanOrPredicate = SigmaBoolean &
  SigmaBooleanOrPredicateAllOf &
  unknown &
  SigmaBooleanOrPredicateAllOfTwo;

export const bigIntsSigmaBooleanOrPredicate: Array<string> = [
  ...bigIntsSigmaBoolean,
  ...bigIntsSigmaBooleanOrPredicateAllOf,
  ...bigIntsSigmaBooleanOrPredicateAllOfTwo,
];
