/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { SigmaBoolean } from './sigmaBoolean';
import { bigIntsSigmaBoolean } from './sigmaBoolean';
import type { SigmaBooleanOrPredicateAllOf } from './sigmaBooleanOrPredicateAllOf';
import { bigIntsSigmaBooleanOrPredicateAllOf } from './sigmaBooleanOrPredicateAllOf';
import type { SigmaBooleanOrPredicateAllOfTwo } from './sigmaBooleanOrPredicateAllOfTwo';

import { bigIntsSigmaBooleanOrPredicateAllOfTwo } from './sigmaBooleanOrPredicateAllOfTwo';

export type SigmaBooleanOrPredicate = SigmaBoolean &
  SigmaBooleanOrPredicateAllOf &
  unknown &
  SigmaBooleanOrPredicateAllOfTwo;

export const bigIntsSigmaBooleanOrPredicate = [
  ...bigIntsSigmaBoolean,
  ...bigIntsSigmaBooleanOrPredicateAllOf,
  ...bigIntsSigmaBooleanOrPredicateAllOfTwo,
];
