/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { SigmaBoolean } from './sigmaBoolean';
import { bigIntsSigmaBoolean } from './sigmaBoolean';

export type SigmaBooleanThresholdPredicateAllOfTwo = {
  args?: SigmaBoolean[];
};
export const bigIntsSigmaBooleanThresholdPredicateAllOfTwo: Array<string> = [
  ...bigIntsSigmaBoolean.map((item) => (item === '' ? 'args' : `args.${item}`)),
];
