/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.22
 */
import type { SnapshotsInfoAvailableManifestsItem } from './snapshotsInfoAvailableManifestsItem';

import { bigIntsSnapshotsInfoAvailableManifestsItem } from './snapshotsInfoAvailableManifestsItem';

export interface SnapshotsInfo {
  /** Map of available manifests height -> manifestId */
  availableManifests: SnapshotsInfoAvailableManifestsItem[];
}

export const bigIntsSnapshotsInfo = [
  ...bigIntsSnapshotsInfoAvailableManifestsItem.map((item) =>
    item === '' ? 'availableManifests' : `availableManifests.${item}`
  ),
];
