/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */

/**
 * Base-16 encoded serialized Sigma-state value
 */
export type SValue = string;
export const bigIntsSValue: Array<string> = [];
