/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { TrackInfoRequested } from './trackInfoRequested';
import { bigIntsTrackInfoRequested } from './trackInfoRequested';
import type { TrackInfoReceived } from './trackInfoReceived';

import { bigIntsTrackInfoReceived } from './trackInfoReceived';

export interface TrackInfo {
  invalidModifierApproxSize: number;
  /** Currently requested modifiers */
  requested: TrackInfoRequested;
  /** Received modifiers */
  received: TrackInfoReceived;
}

export const bigIntsTrackInfo = [
  ...bigIntsTrackInfoRequested.map((item) => `requested.${item}`),
  ...bigIntsTrackInfoReceived.map((item) => `received.${item}`),
];
