/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { RequestedInfoByModifierId } from './requestedInfoByModifierId';

import { bigIntsRequestedInfoByModifierId } from './requestedInfoByModifierId';

/**
 * Currently requested modifiers
 */
export type TrackInfoRequested = { [key: string]: RequestedInfoByModifierId };
export const bigIntsTrackInfoRequested: Array<string> = [];
