/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { UnsignedErgoTransaction } from './unsignedErgoTransaction';
import { bigIntsUnsignedErgoTransaction } from './unsignedErgoTransaction';
import type { TransactionHintsBag } from './transactionHintsBag';
import { bigIntsTransactionHintsBag } from './transactionHintsBag';
import type { TransactionSigningRequestSecrets } from './transactionSigningRequestSecrets';

import { bigIntsTransactionSigningRequestSecrets } from './transactionSigningRequestSecrets';

/**
 * A request to sign a transaction with secrets provided
 */
export interface TransactionSigningRequest {
  /** Unsigned transaction to sign */
  tx: UnsignedErgoTransaction;
  /** Optional list of inputs to be used in serialized form */
  inputsRaw?: string[];
  /** Optional list of inputs to be used in serialized form */
  dataInputsRaw?: string[];
  /** Optional list of hints used for signing */
  hints?: TransactionHintsBag;
  /** Secrets used for signing */
  secrets: TransactionSigningRequestSecrets;
}

export const bigIntsTransactionSigningRequest = [
  ...bigIntsUnsignedErgoTransaction.map((item) =>
    item === '' ? 'tx' : `tx.${item}`
  ),
  ...bigIntsTransactionHintsBag.map((item) =>
    item === '' ? 'hints' : `hints.${item}`
  ),
  ...bigIntsTransactionSigningRequestSecrets.map((item) =>
    item === '' ? 'secrets' : `secrets.${item}`
  ),
];
