/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { UnsignedErgoTransaction } from './unsignedErgoTransaction';
import type { TransactionHintsBag } from './transactionHintsBag';
import type { TransactionSigningRequestSecrets } from './transactionSigningRequestSecrets';

/**
 * A request to sign a transaction with secrets provided
 */
export interface TransactionSigningRequest {
  /** Unsigned transaction to sign */
  tx: UnsignedErgoTransaction;
  /** Optional list of inputs to be used in serialized form */
  inputsRaw?: string[];
  /** Optional list of inputs to be used in serialized form */
  dataInputsRaw?: string[];
  /** Optional list of hints used for signing */
  hints?: TransactionHintsBag;
  /** Secrets used for signing */
  secrets: TransactionSigningRequestSecrets;
}
