/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

/**
 * Base16-encoded transaction id bytes
 */
export type TransactionId = string;
export const bigIntsTransactionId: Array<string> = [];
