/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { TransactionId } from './transactionId';
import type { ErgoTransactionUnsignedInput } from './ergoTransactionUnsignedInput';
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';

/**
 * Unsigned Ergo transaction
 */
export interface UnsignedErgoTransaction {
  id?: TransactionId;
  /** Unsigned inputs of the transaction */
  inputs: ErgoTransactionUnsignedInput[];
  /** Data inputs of the transaction */
  dataInputs: ErgoTransactionDataInput[];
  /** Outputs of the transaction */
  outputs: ErgoTransactionOutput[];
}
