/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import { bigIntsErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';
import type { ErgoTransactionUnsignedInput } from './ergoTransactionUnsignedInput';
import { bigIntsErgoTransactionUnsignedInput } from './ergoTransactionUnsignedInput';
import type { TransactionId } from './transactionId';
import { bigIntsTransactionId } from './transactionId';

/**
 * Unsigned Ergo transaction
 */
export interface UnsignedErgoTransaction {
  id?: TransactionId;
  /** Unsigned inputs of the transaction */
  inputs: ErgoTransactionUnsignedInput[];
  /** Data inputs of the transaction */
  dataInputs: ErgoTransactionDataInput[];
  /** Outputs of the transaction */
  outputs: ErgoTransactionOutput[];
}

export const bigIntsUnsignedErgoTransaction: Array<string> = [
  ...bigIntsTransactionId.map((item) => (item === '' ? 'id' : `id.${item}`)),
  ...bigIntsErgoTransactionUnsignedInput.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`,
  ),
  ...bigIntsErgoTransactionDataInput.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`,
  ),
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`,
  ),
];
