/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */
import type { TransactionId } from './transactionId';
import type { ErgoTransactionInput } from './ergoTransactionInput';
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';

/**
 * Transaction augmented with some useful information
 */
export interface WalletTransaction {
  id?: TransactionId;
  /** Transaction inputs */
  inputs: ErgoTransactionInput[];
  /** Transaction data inputs */
  dataInputs: ErgoTransactionDataInput[];
  /** Transaction outputs */
  outputs: ErgoTransactionOutput[];
  /** Height of a block the transaction was included in */
  inclusionHeight: bigint;
  /** Number of transaction confirmations */
  numConfirmations: bigint;
  /** Scan identifiers the transaction relates to */
  scans: bigint[];
  /** Size in bytes */
  size?: bigint;
}
