/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoAddress } from './ergoAddress';
import { bigIntsErgoAddress } from './ergoAddress';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';
import type { ModifierId } from './modifierId';
import { bigIntsModifierId } from './modifierId';

export interface WalletBox {
  box: ErgoTransactionOutput;
  /**
   * Number of confirmations, if the box is included into the blockchain
   * @minimum 0
   * @nullable
   */
  confirmationsNum: number | null;
  address: ErgoAddress;
  /** Transaction which created the box */
  creationTransaction: ModifierId;
  /**
   * Transaction which created the box
   * @nullable
   */
  spendingTransaction: ModifierId;
  /**
   * The height the box was spent at
   * @minimum 0
   * @nullable
   */
  spendingHeight: number | null;
  /**
   * The height the transaction containing the box was included in a block at
   * @minimum 0
   */
  inclusionHeight: number;
  /** A flag signalling whether the box is created on main chain */
  onchain: boolean;
  /** A flag signalling whether the box was spent */
  spent: boolean;
  /** An index of a box in the creating transaction */
  creationOutIndex: number;
  /** Scan identifiers the box relates to */
  scans: number[];
}

export const bigIntsWalletBox: Array<string> = [
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'box' : `box.${item}`,
  ),
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`,
  ),
  ...bigIntsModifierId.map((item) =>
    item === '' ? 'creationTransaction' : `creationTransaction.${item}`,
  ),
  ...bigIntsModifierId.map((item) =>
    item === '' ? 'spendingTransaction' : `spendingTransaction.${item}`,
  ),
];
