/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.1
 */
import type { ErgoAddress } from './ergoAddress';

import { bigIntsErgoAddress } from './ergoAddress';

export type WalletUpdateChangeAddressBody = {
  address: ErgoAddress;
};

export const bigIntsWalletUpdateChangeAddressBody: Array<string> = [
  ...bigIntsErgoAddress.map((item) =>
    item === '' ? 'address' : `address.${item}`
  ),
];
