/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */
import type { ErgoTransactionDataInput } from './ergoTransactionDataInput';
import { bigIntsErgoTransactionDataInput } from './ergoTransactionDataInput';
import type { ErgoTransactionInput } from './ergoTransactionInput';
import { bigIntsErgoTransactionInput } from './ergoTransactionInput';
import type { ErgoTransactionOutput } from './ergoTransactionOutput';
import { bigIntsErgoTransactionOutput } from './ergoTransactionOutput';
import type { TransactionId } from './transactionId';
import { bigIntsTransactionId } from './transactionId';

/**
 * Transaction augmented with some useful information
 */
export interface WalletTransaction {
  id?: TransactionId;
  /** Transaction inputs */
  inputs: ErgoTransactionInput[];
  /** Transaction data inputs */
  dataInputs: ErgoTransactionDataInput[];
  /** Transaction outputs */
  outputs: ErgoTransactionOutput[];
  /** Height of a block the transaction was included in */
  inclusionHeight: number;
  /** Number of transaction confirmations */
  numConfirmations: number;
  /** Scan identifiers the transaction relates to */
  scans: number[];
  /** Size in bytes */
  size?: number;
}

export const bigIntsWalletTransaction: Array<string> = [
  ...bigIntsTransactionId.map((item) => (item === '' ? 'id' : `id.${item}`)),
  ...bigIntsErgoTransactionInput.map((item) =>
    item === '' ? 'inputs' : `inputs.${item}`,
  ),
  ...bigIntsErgoTransactionDataInput.map((item) =>
    item === '' ? 'dataInputs' : `dataInputs.${item}`,
  ),
  ...bigIntsErgoTransactionOutput.map((item) =>
    item === '' ? 'outputs' : `outputs.${item}`,
  ),
];
