/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.7
 */

export type WalletTransactionsParams = {
  /**
   * Minimal tx inclusion height
   */
  minInclusionHeight?: number;
  /**
   * Maximal tx inclusion height
   */
  maxInclusionHeight?: number;
  /**
   * Minimal confirmations number
   */
  minConfirmations?: number;
  /**
   * Maximal confirmations number
   */
  maxConfirmations?: number;
};
