/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 6.0.3
 */

export type WalletRescanBody = {
  /** @minimum 0 */
  fromHeight: number;
};
export const bigIntsWalletRescanBody: Array<string> = [];
