/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 * OpenAPI spec version: 5.0.10
 */
import type { ProofOfUpcomingTransactions } from './proofOfUpcomingTransactions';

import { bigIntsProofOfUpcomingTransactions } from './proofOfUpcomingTransactions';

/**
 * Block candidate related data for external miner to perform work
 */
export interface WorkMessage {
  /** Base16-encoded block header bytes without PoW solution */
  msg: string;
  /** Work target value */
  b: number;
  /** Base16-encoded miner public key */
  pk: string;
  proof?: ProofOfUpcomingTransactions;
}
export const bigIntsWorkMessage = [
  ...bigIntsProofOfUpcomingTransactions.map((item) => `proof.${item}`),
];
