/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { TokenAmount } from './tokenAmount';
import { bigIntsTokenAmount } from './tokenAmount';

export interface Balance {
  /** Ergo balance */
  nanoErgs: bigint;
  /** Tokens balances */
  tokens?: TokenAmount[];
}

export const bigIntsBalance: Array<string> = [
  'nanoErgs',
  ...bigIntsTokenAmount.map((item) =>
    item === '' ? 'tokens' : `tokens.${item}`,
  ),
];
