/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { TokenAmount } from './tokenAmount';

export interface Balance {
  /** Ergo balance */
  nanoErgs: number;
  /** Tokens balances */
  tokens?: TokenAmount[];
}
