/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { TokenAmount } from './tokenAmount';

import { bigIntsTokenAmount } from './tokenAmount';

export interface Balance {
  /** Ergo balance */
  nanoErgs: bigint;
  /** Tokens balances */
  tokens?: TokenAmount[];
}
export const bigIntsBalance = [
  'nanoErgs',
  ...bigIntsTokenAmount.map((item) => `tokens.${item}`),
];
