/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { BlockPowSolutions } from './blockPowSolutions';

export interface BlockHeader {
  /** Modifier ID */
  id: string;
  /** Modifier ID */
  parentId: string;
  version: bigint;
  timestamp: bigint;
  height: bigint;
  nBits: bigint;
  votes: string;
  /** Hex-encoded string */
  stateRoot: string;
  /** Hex-encoded string */
  adProofsRoot: string;
  /** Hex-encoded string */
  transactionsRoot: string;
  /** Hex-encoded string */
  extensionHash: string;
  powSolutions: BlockPowSolutions;
}
