/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { BlockPowSolutions } from './blockPowSolutions';

import { bigIntsBlockPowSolutions } from './blockPowSolutions';

export interface BlockHeader {
  /** Modifier ID */
  id: string;
  /** Modifier ID */
  parentId: string;
  version: number;
  timestamp: bigint;
  height: number;
  nBits: bigint;
  votes: string;
  /** Hex-encoded string */
  stateRoot: string;
  /** Hex-encoded string */
  adProofsRoot: string;
  /** Hex-encoded string */
  transactionsRoot: string;
  /** Hex-encoded string */
  extensionHash: string;
  powSolutions: BlockPowSolutions;
}

export const bigIntsBlockHeader = [
  'timestamp',
  'nBits',
  ...bigIntsBlockPowSolutions.map((item) =>
    item === '' ? 'powSolutions' : `powSolutions.${item}`
  ),
];
