/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

/**
 * Pairs of (register ID, register value) this box should contain
 */
export type BoxQueryRegisters = { [key: string]: string };
export const bigIntsBoxQueryRegisters = [];
