/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

/**
 * Pairs of (constant index, constant value) this box should contain
 */
export type BoxQueryConstants = { [key: string]: string };
