/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

/**
 * Pairs of (constant index, constant value) this box should contain
 */
export type BoxQueryConstants = { [key: string]: string };
export const bigIntsBoxQueryConstants = [];
