/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type DataInputInfoAdditionalRegisters = {
  [key: string]: {
    serializedValue: string;
    sigmaType: string;
    renderedValue: string;
  };
};
export const bigIntsDataInputInfoAdditionalRegisters: Array<string> = [];
