/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { AssetInstanceInfo } from './assetInstanceInfo';
import { bigIntsAssetInstanceInfo } from './assetInstanceInfo';
import type { DataInputInfoAdditionalRegisters } from './dataInputInfoAdditionalRegisters';

import { bigIntsDataInputInfoAdditionalRegisters } from './dataInputInfoAdditionalRegisters';

export interface DataInputInfo {
  /** ID of the corresponding box */
  boxId: string;
  /** Number of nanoErgs in the corresponding box */
  value: bigint;
  /** Index of the input in a transaction */
  index: number;
  /** Modifier ID */
  outputBlockId: string;
  /** ID of the transaction outputting corresponding box */
  outputTransactionId: string;
  /** Index of the output corresponding this input */
  outputIndex: number;
  /** Hex-encoded string */
  ergoTree: string;
  /** Decoded address of the corresponding box holder */
  address: string;
  assets?: AssetInstanceInfo[];
  additionalRegisters: DataInputInfoAdditionalRegisters;
}

export const bigIntsDataInputInfo = [
  'value',
  ...bigIntsAssetInstanceInfo.map((item) => `assets.${item}`),
  ...bigIntsDataInputInfoAdditionalRegisters.map(
    (item) => `additionalRegisters.${item}`
  ),
];
