/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export interface EpochInfo {
  height: number;
  storageFeeFactor: number;
  minValuePerByte: number;
  maxBlockSize: number;
  maxBlockCost: number;
  blockVersion: number;
  tokenAccessCost: number;
  inputCost: number;
  dataInputCost: number;
  outputCost: number;
}
export const bigIntsEpochInfo = [];
