/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export interface ErgoTreeHuman {
  /** Constants use in ergo script */
  constants: string;
  /** Human readable ergo script */
  script: string;
}
export const bigIntsErgoTreeHuman = [];
