/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { HeaderInfo } from './headerInfo';
import type { TransactionInfo1 } from './transactionInfo1';
import type { BlockExtensionInfo } from './blockExtensionInfo';

/**
 * Full block info
 */
export interface FullBlockInfo {
  header: HeaderInfo;
  blockTransactions?: TransactionInfo1[];
  extension: BlockExtensionInfo;
  /** Serialized hex-encoded AD Proofs */
  adProofs?: string;
}
