/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AddressesP1TransactionsParams = {
  offset?: number;
  limit?: number;
  /**
   * Display only address inputs/outputs in transaction
   */
  concise?: boolean;
  fromHeight?: number;
  toHeight?: number;
};
export const bigIntsGetApiV1AddressesP1TransactionsParams = [];
