/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AddressesP1TransactionsParams = {
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
  /**
   * Display only address inputs/outputs in transaction
   */
  concise?: boolean;
  /**
   * @minimum 0
   */
  fromHeight?: number;
  /**
   * @minimum 1
   */
  toHeight?: number;
};
export const bigIntsGetApiV1AddressesP1TransactionsParams: Array<string> = [];
