/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BoxesByergotreetemplatehashP1StreamParams = {
  /**
   * @minimum 0
   */
  minHeight: number;
  /**
   * @minimum 1
   */
  maxHeight: number;
};
export const bigIntsGetApiV1BoxesByergotreetemplatehashP1StreamParams: Array<string> =
  [];
