/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1TransactionsByinputsscripttemplatehashP1Params = {
  offset?: number;
  limit?: number;
  sortDirection?: string;
};
export const bigIntsGetApiV1TransactionsByinputsscripttemplatehashP1Params = [];
