/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BoxesByglobalindexStreamParams = {
  /**
   * Min global index (in blockchain) of an on-chain entity
   */
  minGix: bigint;
  limit: bigint;
};
