/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BoxesUnspentByergotreeP1Params = {
  offset?: number;
  limit?: number;
  sortDirection?: string;
};
