/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BoxesUnspentUnconfirmedByaddressP1Params = {
  sortDirection?: string;
};
export const bigIntsGetApiV1BoxesUnspentUnconfirmedByaddressP1Params: Array<string> =
  [];
