/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BoxesUnspentByergotreetemplatehashP1Params = {
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
};
export const bigIntsGetApiV1BoxesUnspentByergotreetemplatehashP1Params: Array<string> =
  [];
