/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BoxesUnspentBylastepochsStreamParams = {
  /**
   * @maximum 1536
   */
  lastEpochs: number;
};
export const bigIntsGetApiV1BoxesUnspentBylastepochsStreamParams: Array<string> =
  [];
