/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BlocksByglobalindexStreamParams = {
  /**
   * Min global index (in blockchain) of an on-chain entity
   */
  minGix: bigint;
  limit: number;
};
export const bigIntsGetApiV1BlocksByglobalindexStreamParams = ['minGix'];
