/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BlocksStreamSummaryParams = {
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 1
   * @maximum 1536
   */
  limit?: number;
  sortBy?: string;
  sortDirection?: string;
};
export const bigIntsGetApiV1BlocksStreamSummaryParams: Array<string> = [];
