/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AssetsSearchBytokenidParams = {
  query: string;
  offset?: number;
  limit?: number;
};
export const bigIntsGetApiV1AssetsSearchBytokenidParams = [];
