/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type InputInfoAdditionalRegisters = {
  [key: string]: {
    serializedValue: string;
    sigmaType: string;
    renderedValue: string;
  };
};
export const bigIntsInputInfoAdditionalRegisters = [];
