/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { OutputInfo } from './outputInfo';

export interface ItemsOutputInfo {
  /** Items in selection */
  items?: OutputInfo[];
  /** Total qty of items */
  total: number;
}
