/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { BlockInfo } from './blockInfo';
import { bigIntsBlockInfo } from './blockInfo';

export interface ItemsBlockInfo {
  /** Items in selection */
  items?: BlockInfo[];
  /** Total qty of items */
  total: number;
}
export const bigIntsItemsBlockInfo: Array<string> = [
  ...bigIntsBlockInfo.map((item) => (item === '' ? 'items' : `items.${item}`)),
];
