/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { OutputInfo } from './outputInfo';

import { bigIntsOutputInfo } from './outputInfo';

export interface ItemsOutputInfo {
  /** Items in selection */
  items?: OutputInfo[];
  /** Total qty of items */
  total: number;
}
export const bigIntsItemsOutputInfo = [
  ...bigIntsOutputInfo.map((item) => (item === '' ? 'items' : `items.${item}`)),
];
