/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { BlockHeader } from './blockHeader';

import { bigIntsBlockHeader } from './blockHeader';

export interface ItemsBlockHeader {
  /** Items in selection */
  items?: BlockHeader[];
  /** Total qty of items */
  total: number;
}
export const bigIntsItemsBlockHeader = [
  ...bigIntsBlockHeader.map((item) => `items.${item}`),
];
