/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { AssetInfo } from './assetInfo';

export interface ItemsAssetInfo {
  /** Items in selection */
  items?: AssetInfo[];
  /** Total qty of items */
  total: bigint;
}
