/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { TransactionInfo } from './transactionInfo';

export interface ItemsA {
  /** Items in selection */
  items?: TransactionInfo[];
  /** Total qty of items */
  total: bigint;
}
