/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { TransactionInfo } from './transactionInfo';
import { bigIntsTransactionInfo } from './transactionInfo';

export interface ItemsTransactionInfo {
  /** Items in selection */
  items?: TransactionInfo[];
  /** Total qty of items */
  total: number;
}

export const bigIntsItemsTransactionInfo: Array<string> = [
  ...bigIntsTransactionInfo.map((item) =>
    item === '' ? 'items' : `items.${item}`,
  ),
];
