/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export interface ItemsString {
  /** Items in selection */
  items?: string[];
  /** Total qty of items */
  total: number;
}
export const bigIntsItemsString: Array<string> = [];
