/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { Nil } from './nil';
import { bigIntsNil } from './nil';
import type { BlockInfo } from './blockInfo';

import { bigIntsBlockInfo } from './blockInfo';

export type ListBlockInfo = Nil | BlockInfo[];
export const bigIntsListBlockInfo = [];
