/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { BlockSummaryV1 } from './blockSummaryV1';
import { bigIntsBlockSummaryV1 } from './blockSummaryV1';
import type { Nil } from './nil';
import { bigIntsNil } from './nil';

export type ListBlockSummaryV1 = Nil | BlockSummaryV1[];
export const bigIntsListBlockSummaryV1: Array<string> = [
  ...bigIntsNil,
  ...bigIntsBlockSummaryV1,
];
