/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { Nil } from './nil';
import type { BlockSummaryV1 } from './blockSummaryV1';

export type ListBlockSummaryV1 = Nil | BlockSummaryV1[];
