/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type MOutputInfoAdditionalRegisters = { [key: string]: string };
export const bigIntsMOutputInfoAdditionalRegisters = [];
