/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { EpochInfo } from './epochInfo';
import { bigIntsEpochInfo } from './epochInfo';

export interface NetworkState {
  /** Modifier ID */
  lastBlockId: string;
  height: number;
  maxBoxGix: bigint;
  maxTxGix: bigint;
  params: EpochInfo;
}

export const bigIntsNetworkState: Array<string> = [
  'maxBoxGix',
  'maxTxGix',
  ...bigIntsEpochInfo.map((item) =>
    item === '' ? 'params' : `params.${item}`,
  ),
];
