/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { EpochInfo } from './epochInfo';

export interface NetworkState {
  /** Modifier ID */
  lastBlockId: string;
  height: bigint;
  maxBoxGix: bigint;
  maxTxGix: bigint;
  params: EpochInfo;
}
