/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { EpochInfo } from './epochInfo';

import { bigIntsEpochInfo } from './epochInfo';

export interface NetworkState {
  /** Modifier ID */
  lastBlockId: string;
  height: number;
  maxBoxGix: bigint;
  maxTxGix: bigint;
  params: EpochInfo;
}
export const bigIntsNetworkState = [
  'maxBoxGix',
  'maxTxGix',
  ...bigIntsEpochInfo.map((item) => `params.${item}`),
];
