/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export interface Nil {
  [key: string]: unknown;
}
export const bigIntsNil: Array<string> = [];
