/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export type PostApiV1BoxesUnspentSearchParams = {
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
};
export const bigIntsPostApiV1BoxesUnspentSearchParams: Array<string> = [];
