/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { Balance } from './balance';
import { bigIntsBalance } from './balance';

export interface TotalBalance {
  confirmed: Balance;
  unconfirmed: Balance;
}

export const bigIntsTotalBalance: Array<string> = [
  ...bigIntsBalance.map((item) =>
    item === '' ? 'confirmed' : `confirmed.${item}`,
  ),
  ...bigIntsBalance.map((item) =>
    item === '' ? 'unconfirmed' : `unconfirmed.${item}`,
  ),
];
