/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { Balance } from './balance';

import { bigIntsBalance } from './balance';

export interface TotalBalance {
  confirmed: Balance;
  unconfirmed: Balance;
}

export const bigIntsTotalBalance = [
  ...bigIntsBalance.map((item) => `confirmed.${item}`),
  ...bigIntsBalance.map((item) => `unconfirmed.${item}`),
];
