/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { InputInfo1 } from './inputInfo1';
import type { DataInputInfo1 } from './dataInputInfo1';
import type { OutputInfo1 } from './outputInfo1';

export interface TransactionInfo1 {
  /** Transaction ID */
  id: string;
  /** ID of the corresponding header */
  headerId: string;
  /** Height of the block the transaction was included in */
  inclusionHeight: bigint;
  /** Timestamp the transaction got into the network */
  timestamp: bigint;
  /** Index of a transaction inside a block */
  index: bigint;
  /** Number of transaction confirmations */
  confirmationsCount: bigint;
  inputs?: InputInfo1[];
  dataInputs?: DataInputInfo1[];
  outputs?: OutputInfo1[];
}
