/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

/**
 * Block votes (3 bytes)
 */
export interface Tuple3ByteByteByte {
  _1: number;
  _2: number;
  _3: number;
}
export const bigIntsTuple3ByteByteByte: Array<string> = [];
