/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export interface TxIdResponse {
  /** Id of submitted transaction */
  id: string;
}
