/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */

export interface UnknownErr {
  status: number;
  reason: string;
}
export const bigIntsUnknownErr: Array<string> = [];
