/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Ergo Explorer API v1
 * OpenAPI spec version: 1.0
 */
import type { UInputInfo } from './uInputInfo';
import type { UDataInputInfo } from './uDataInputInfo';
import type { UOutputInfo } from './uOutputInfo';

export interface UTransactionInfo {
  /** Transaction ID */
  id: string;
  /** Timestamp the transaction got into the network */
  creationTimestamp: bigint;
  inputs?: UInputInfo[];
  dataInputs?: UDataInputInfo[];
  outputs?: UOutputInfo[];
  /** Transaction size in bytes */
  size: bigint;
}
