/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Koios API
 * Koios is best described as a Decentralized and Elastic RESTful query layer for exploring data on Cardano blockchain to consume within applications/wallets/explorers/etc. This page not only provides an OpenAPI Spec for live implementation, but also ability to execute live demo from client browser against each endpoint with pre-filled examples.

# API Usage

The endpoints served by Koios can be browsed from the left side bar of this site. You will find that almost each endpoint has an example that you can `Try` and will help you get an example in shell using cURL. For public queries, you do not need to register yourself - you can simply use them as per the examples provided on individual endpoints. But in addition, the [PostgREST API](https://postgrest.org/en/stable/api.html) used underneath provides a handful of features that can be quite handy for you to improve your queries to directly grab very specific information pertinent to your calls, reducing data you download and process.

## Vertical Filtering

Instead of returning entire row, you can elect which rows you would like to fetch from the endpoint by using the `select` parameter with corresponding columns separated by commas. See example below (first is complete information for tip, while second command gives us 3 columns we are interested in):<br><br>

``` bash
curl "https://api.koios.rest/api/v1/tip"

# [{"hash":"4d44c8a453e677f933c3df42ebcf2fe45987c41268b9cfc9b42ae305e8c3d99a","epoch_no":317,"abs_slot":51700871,"epoch_slot":120071,"block_height":6806994,"block_time":1643267162}]

curl "https://api.koios.rest/api/v1/blocks?select=epoch_no,epoch_slot,block_height"

# [{"epoch_no":317,"epoch_slot":120071,"block_height":6806994}]
```

## Horizontal Filtering

You can filter the returned output based on specific conditions using operators against a column within returned result. Consider an example where you would want to query blocks minted in first 3 minutes of epoch 250 (i.e. epoch_slot was less than 180). To do so your query would look like below:<br><br>
``` bash
curl "https://api.koios.rest/api/v1/blocks?epoch_no=eq.250&epoch_slot=lt.180"

# [{"hash":"8fad2808ac6b37064a0fa69f6fe065807703d5235a57442647bbcdba1c02faf8","epoch_no":250,"abs_slot":22636942,"epoch_slot":142,"block_height":5385757,"block_time":1614203233,"tx_count":65,"vrf_key":"vrf_vk14y9pjprzlsjvjt66mv5u7w7292sxp3kn4ewhss45ayjga5vurgaqhqknuu","pool":null,"op_cert_counter":2},
#  {"hash":"9d33b02badaedc0dedd0d59f3e0411e5fb4ac94217fb5ee86719e8463c570e16","epoch_no":250,"abs_slot":22636800,"epoch_slot":0,"block_height":5385756,"block_time":1614203091,"tx_count":10,"vrf_key":"vrf_vk1dkfsejw3h2k7tnguwrauqfwnxa7wj3nkp3yw2yw3400c4nlkluwqzwvka6","pool":null,"op_cert_counter":2}]
```

Here, we made use of `eq.` operator to denote a filter of "value equal to" against `epoch_no` column. Similarly, we added a filter using `lt.` operator to denote a filter of "values lower than" against `epoch_slot` column. You can find a complete list of operators supported in PostgREST documentation (commonly used ones extracted below):

|Abbreviation|In PostgreSQL|Meaning                                    |
|------------|-------------|-------------------------------------------|
|eq          |`=`          |equals                                     |
|gt          |`>`          |greater than                               |
|gte         |`>=`         |greater than or equal                      |
|lt          |`<`          |less than                                  |
|lte         |`<=`         |less than or equal                         |
|neq         |`<>` or `!=` |not equal                                  |
|like        |`LIKE`       |LIKE operator (use * in place of %)        |
|in          |`IN`         |one of a list of values, e.g. `?a=in.("hi,there","yes,you")`|
|is          |`IS`         |checking for exact equality (null,true,false,unknown)|
|cs          |`@>`         |contains e.g. `?tags=cs.{example, new}`    |
|cd          |`<@`         |contained in e.g. `?values=cd.{1,2,3}`     |
|not         |`NOT`        |negates another operator                   |
|or          |`OR`         |logical `OR` operator                      |
|and         |`AND`        |logical `AND` operator                     |

## Pagination (offset/limit)

When you query any endpoint in PostgREST, the number of observations returned will be limited to a maximum of 1000 rows (set via `max-rows` config option in the `grest.conf` file. This - however - is a result of a paginated call, wherein the [ up to ] 1000 records you see without any parameters is the first page. If you want to see the next 1000 results, you can always append `offset=1000` to view the next set of results. But what if 1000 is too high for your use-case and you want smaller page? Well, you can specify a smaller limit using parameter `limit`, which will see shortly in an example below. The obvious question at this point that would cross your mind is - how do I know if I need to offset and what range I am querying? This is where headers come in to your aid.  

The default headers returned by PostgREST will include a `Content-Range` field giving a range of observations returned. For large tables, this range could include a wildcard `*` as it is expensive to query exact count of observations from endpoint. But if you would like to get an estimate count without overloading servers, PostgREST can utilise Postgres's own maintenance thread results (which maintain stats for each table) to provide you a count, by specifying a header `"Prefer: count=estimated"`.  

Sounds confusing? Let's see this in practice, to hopefully make it easier.
Consider a simple case where I want query `blocks` endpoint for `block_height` column and focus on `content-range` header to monitor the rows we discussed above.<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?select=block_height" -I | grep -i content-range

# content-range: 0-999/*

```

As we can see above, the number of observations returned was 1000 (range being 0-999), but the total size was not queried to avoid wait times. Now, let's modify this default behaviour to query rows beyond the first 999, but this time - also add another clause to limit results by 500. We can do this using `offset=1000` and `limit=500` as below:<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?select=block_height&offset=1000&limit=500" -I | grep -i content-range

# content-range: 1000-1499/*

```

The above methods for pagination are very useful to keep some of the queries light as well as process the output in smaller pages, making better use of your resources and respecting server timeouts for response times.
However, note that due to the complex nature of some queries that require pre-processing before being subjected to paginations, these may not always be helpful to avoid server timeouts.

## Ordering

You can set a sorting order for returned queries against specific column(s).
Consider example where you want to check `epoch_no` and `epoch_slot` for the first 5 blocks created by a particular pool, i.e. you can set order to ascending based on block_height column and add horizontal filter for that pool ID as below:<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?pool=eq.pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc&order=block_height.asc&limit=5"

# [{"hash":"610b4c7bbebeeb212bd002885048cc33154ba29f39919d62a3d96de05d315706","epoch_no":236,"abs_slot":16594295,"epoch_slot":5495,"block_height":5086774,"block_time":1608160586,"tx_count":1,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"d93d1db5275329ab695d30c06a35124038d8d9af64fc2b0aa082b8aa43da4164","epoch_no":236,"abs_slot":16597729,"epoch_slot":8929,"block_height":5086944,"block_time":1608164020,"tx_count":7,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"dc9496eae64294b46f07eb20499ae6dae4d81fdc67c63c354397db91bda1ee55","epoch_no":236,"abs_slot":16598058,"epoch_slot":9258,"block_height":5086962,"block_time":1608164349,"tx_count":1,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"6ebc7b734c513bc19290d96ca573a09cac9503c5a349dd9892b9ab43f917f9bd","epoch_no":236,"abs_slot":16601491,"epoch_slot":12691,"block_height":5087097,"block_time":1608167782,"tx_count":0,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1},
# {"hash":"2eac97548829fc312858bc56a40f7ce3bf9b0ca27ee8530283ccebb3963de1c0","epoch_no":236,"abs_slot":16602308,"epoch_slot":13508,"block_height":5087136,"block_time":1608168599,"tx_count":1,"vrf_key":"vrf_vk18x0e7dx8j37gdxftnn8ru6jcxs7n6acdazc4ykeda2ygjwg9a7ls7ns699","pool":"pool155efqn9xpcf73pphkk88cmlkdwx4ulkg606tne970qswczg3asc","op_cert_counter":1}]
```

## Response Formats

You can get the results from the PostgREST endpoints in CSV or JSON formats. The default response format will always be JSON, but if you'd like to switch, you can do so by specifying header `'Accept: text/csv'` or `'Accept: application/json'`.
Below is an example of JSON/CSV output making use of above to print first in JSON (default), and then override response format to CSV.<br><br>

``` bash
curl -s "https://api.koios.rest/api/v1/blocks?select=epoch_no,epoch_slot,block_time&limit=3"

# [{"epoch_no":318,"epoch_slot":27867,"block_time":1643606958},
# {"epoch_no":318,"epoch_slot":27841,"block_time":1643606932},
# {"epoch_no":318,"epoch_slot":27839,"block_time":1643606930}]

curl -s "https://api.koios.rest/api/v1/blocks?select=epoch_no,epoch_slot,block_time&limit=3" -H "Accept: text/csv"

# epoch_no,epoch_slot,block_time
# 318,28491,1643607582
# 318,28479,1643607570
# 318,28406,1643607497

```

## Limits

While use of Koios is completely free and there are no registration requirements to the usage, the monitoring layer will only restrict spam requests that can potentially cause high amount of load to backends. The emphasis is on using list of objects first, and then [bulk where available] query specific objects to drill down where possible - which forms higher performance results to consumer as well as instance provider. Some basic protection against patterns that could cause unexpected resource spikes are protected as per below:

  - Burst Limit: A single IP can query an endpoint up to 100 times within 10 seconds (that's about 8.64 million requests within a day). The sleep time if a limit is crossed is minimal (60 seconds) for that IP - during which, the monitoring layer will return HTTP Status `429 - Too many requests`.  
  - Pagination/Limits: Any query results fetched will be paginated by 1000 records (you can reduce limit and or control pagination offsets on URL itself, see API > Pagination section for more details).
  - Query timeout: If a query from server takes more than 30 seconds, it will return a HTTP Status of `504 - Gateway timeout`. This is because we would want to ensure you're using the queries optimally, and more often than not - it would indicate that particular endpoint is not optimised (or the network connectivity is not optimal between servers).
  - Payload size limit: Koios supports sending bulk objects to reduce networking costs as well as number of calls users spent. However, this can also become an easy attack surface. Thus, we've had to add a strict limit for request body size to be limited to 1kb for public and 5kb for registered tiers.

Yet, there may be cases where the above restrictions may need exceptions (for example, an explorer or a wallet might need more connections than above - going beyond the Burst Limit). For such cases, it is best to approach the team and we can work towards a solution.

# Authentication

While Koios public tier remains unauthenticated and allows queries without any authentication, it has low limits to prevent actions against an erroraneous query/loop from a consumer. There is also a Free tier which requires setting up Bearer Auth token that is linked to the owner's wallet account (which can be connected to via [Koios website](https://koios.rest/pricing/Pricing.html) ).
The examples across this API site already [supports authentication](/#auth), for you to use in the queries.

# Community projects

A big thank you to the following projects who are already starting to use Koios from early days. A list of tools, libraries and projects utilising Koios (atleast those who'd like to be named) can be found [here](https://www.koios.rest/community.html)

 * OpenAPI spec version: v1.4.2
 */
import type { EpochParamsItemCoinsPerUtxoSize } from './epochParamsItemCoinsPerUtxoSize';
import { bigIntsEpochParamsItemCoinsPerUtxoSize } from './epochParamsItemCoinsPerUtxoSize';
import type { EpochParamsItemCollateralPercent } from './epochParamsItemCollateralPercent';
import { bigIntsEpochParamsItemCollateralPercent } from './epochParamsItemCollateralPercent';
import type { EpochParamsItemCommitteeMaxTermLength } from './epochParamsItemCommitteeMaxTermLength';
import { bigIntsEpochParamsItemCommitteeMaxTermLength } from './epochParamsItemCommitteeMaxTermLength';
import type { EpochParamsItemCommitteeMinSize } from './epochParamsItemCommitteeMinSize';
import { bigIntsEpochParamsItemCommitteeMinSize } from './epochParamsItemCommitteeMinSize';
import type { EpochParamsItemCostModels } from './epochParamsItemCostModels';
import { bigIntsEpochParamsItemCostModels } from './epochParamsItemCostModels';
import type { EpochParamsItemDecentralisation } from './epochParamsItemDecentralisation';
import { bigIntsEpochParamsItemDecentralisation } from './epochParamsItemDecentralisation';
import type { EpochParamsItemDrepActivity } from './epochParamsItemDrepActivity';
import { bigIntsEpochParamsItemDrepActivity } from './epochParamsItemDrepActivity';
import type { EpochParamsItemDrepDeposit } from './epochParamsItemDrepDeposit';
import { bigIntsEpochParamsItemDrepDeposit } from './epochParamsItemDrepDeposit';
import type { EpochParamsItemDvtCommitteeNoConfidence } from './epochParamsItemDvtCommitteeNoConfidence';
import { bigIntsEpochParamsItemDvtCommitteeNoConfidence } from './epochParamsItemDvtCommitteeNoConfidence';
import type { EpochParamsItemDvtCommitteeNormal } from './epochParamsItemDvtCommitteeNormal';
import { bigIntsEpochParamsItemDvtCommitteeNormal } from './epochParamsItemDvtCommitteeNormal';
import type { EpochParamsItemDvtHardForkInitiation } from './epochParamsItemDvtHardForkInitiation';
import { bigIntsEpochParamsItemDvtHardForkInitiation } from './epochParamsItemDvtHardForkInitiation';
import type { EpochParamsItemDvtMotionNoConfidence } from './epochParamsItemDvtMotionNoConfidence';
import { bigIntsEpochParamsItemDvtMotionNoConfidence } from './epochParamsItemDvtMotionNoConfidence';
import type { EpochParamsItemDvtPPEconomicGroup } from './epochParamsItemDvtPPEconomicGroup';
import { bigIntsEpochParamsItemDvtPPEconomicGroup } from './epochParamsItemDvtPPEconomicGroup';
import type { EpochParamsItemDvtPPGovGroup } from './epochParamsItemDvtPPGovGroup';
import { bigIntsEpochParamsItemDvtPPGovGroup } from './epochParamsItemDvtPPGovGroup';
import type { EpochParamsItemDvtPPNetworkGroup } from './epochParamsItemDvtPPNetworkGroup';
import { bigIntsEpochParamsItemDvtPPNetworkGroup } from './epochParamsItemDvtPPNetworkGroup';
import type { EpochParamsItemDvtPPTechnicalGroup } from './epochParamsItemDvtPPTechnicalGroup';
import { bigIntsEpochParamsItemDvtPPTechnicalGroup } from './epochParamsItemDvtPPTechnicalGroup';
import type { EpochParamsItemDvtTreasuryWithdrawal } from './epochParamsItemDvtTreasuryWithdrawal';
import { bigIntsEpochParamsItemDvtTreasuryWithdrawal } from './epochParamsItemDvtTreasuryWithdrawal';
import type { EpochParamsItemDvtUpdateToConstitution } from './epochParamsItemDvtUpdateToConstitution';
import { bigIntsEpochParamsItemDvtUpdateToConstitution } from './epochParamsItemDvtUpdateToConstitution';
import type { EpochParamsItemExtraEntropy } from './epochParamsItemExtraEntropy';
import { bigIntsEpochParamsItemExtraEntropy } from './epochParamsItemExtraEntropy';
import type { EpochParamsItemGovActionDeposit } from './epochParamsItemGovActionDeposit';
import { bigIntsEpochParamsItemGovActionDeposit } from './epochParamsItemGovActionDeposit';
import type { EpochParamsItemGovActionLifetime } from './epochParamsItemGovActionLifetime';
import { bigIntsEpochParamsItemGovActionLifetime } from './epochParamsItemGovActionLifetime';
import type { EpochParamsItemInfluence } from './epochParamsItemInfluence';
import { bigIntsEpochParamsItemInfluence } from './epochParamsItemInfluence';
import type { EpochParamsItemKeyDeposit } from './epochParamsItemKeyDeposit';
import { bigIntsEpochParamsItemKeyDeposit } from './epochParamsItemKeyDeposit';
import type { EpochParamsItemMaxBhSize } from './epochParamsItemMaxBhSize';
import { bigIntsEpochParamsItemMaxBhSize } from './epochParamsItemMaxBhSize';
import type { EpochParamsItemMaxBlockExMem } from './epochParamsItemMaxBlockExMem';
import { bigIntsEpochParamsItemMaxBlockExMem } from './epochParamsItemMaxBlockExMem';
import type { EpochParamsItemMaxBlockExSteps } from './epochParamsItemMaxBlockExSteps';
import { bigIntsEpochParamsItemMaxBlockExSteps } from './epochParamsItemMaxBlockExSteps';
import type { EpochParamsItemMaxBlockSize } from './epochParamsItemMaxBlockSize';
import { bigIntsEpochParamsItemMaxBlockSize } from './epochParamsItemMaxBlockSize';
import type { EpochParamsItemMaxCollateralInputs } from './epochParamsItemMaxCollateralInputs';
import { bigIntsEpochParamsItemMaxCollateralInputs } from './epochParamsItemMaxCollateralInputs';
import type { EpochParamsItemMaxEpoch } from './epochParamsItemMaxEpoch';
import { bigIntsEpochParamsItemMaxEpoch } from './epochParamsItemMaxEpoch';
import type { EpochParamsItemMaxTxExMem } from './epochParamsItemMaxTxExMem';
import { bigIntsEpochParamsItemMaxTxExMem } from './epochParamsItemMaxTxExMem';
import type { EpochParamsItemMaxTxExSteps } from './epochParamsItemMaxTxExSteps';
import { bigIntsEpochParamsItemMaxTxExSteps } from './epochParamsItemMaxTxExSteps';
import type { EpochParamsItemMaxTxSize } from './epochParamsItemMaxTxSize';
import { bigIntsEpochParamsItemMaxTxSize } from './epochParamsItemMaxTxSize';
import type { EpochParamsItemMaxValSize } from './epochParamsItemMaxValSize';
import { bigIntsEpochParamsItemMaxValSize } from './epochParamsItemMaxValSize';
import type { EpochParamsItemMinFeeA } from './epochParamsItemMinFeeA';
import { bigIntsEpochParamsItemMinFeeA } from './epochParamsItemMinFeeA';
import type { EpochParamsItemMinFeeB } from './epochParamsItemMinFeeB';
import { bigIntsEpochParamsItemMinFeeB } from './epochParamsItemMinFeeB';
import type { EpochParamsItemMinFeeRefScriptCostPerByte } from './epochParamsItemMinFeeRefScriptCostPerByte';
import { bigIntsEpochParamsItemMinFeeRefScriptCostPerByte } from './epochParamsItemMinFeeRefScriptCostPerByte';
import type { EpochParamsItemMinPoolCost } from './epochParamsItemMinPoolCost';
import { bigIntsEpochParamsItemMinPoolCost } from './epochParamsItemMinPoolCost';
import type { EpochParamsItemMinUtxoValue } from './epochParamsItemMinUtxoValue';
import { bigIntsEpochParamsItemMinUtxoValue } from './epochParamsItemMinUtxoValue';
import type { EpochParamsItemMonetaryExpandRate } from './epochParamsItemMonetaryExpandRate';
import { bigIntsEpochParamsItemMonetaryExpandRate } from './epochParamsItemMonetaryExpandRate';
import type { EpochParamsItemNonce } from './epochParamsItemNonce';
import { bigIntsEpochParamsItemNonce } from './epochParamsItemNonce';
import type { EpochParamsItemOptimalPoolCount } from './epochParamsItemOptimalPoolCount';
import { bigIntsEpochParamsItemOptimalPoolCount } from './epochParamsItemOptimalPoolCount';
import type { EpochParamsItemPoolDeposit } from './epochParamsItemPoolDeposit';
import { bigIntsEpochParamsItemPoolDeposit } from './epochParamsItemPoolDeposit';
import type { EpochParamsItemPriceMem } from './epochParamsItemPriceMem';
import { bigIntsEpochParamsItemPriceMem } from './epochParamsItemPriceMem';
import type { EpochParamsItemPriceStep } from './epochParamsItemPriceStep';
import { bigIntsEpochParamsItemPriceStep } from './epochParamsItemPriceStep';
import type { EpochParamsItemProtocolMajor } from './epochParamsItemProtocolMajor';
import { bigIntsEpochParamsItemProtocolMajor } from './epochParamsItemProtocolMajor';
import type { EpochParamsItemProtocolMinor } from './epochParamsItemProtocolMinor';
import { bigIntsEpochParamsItemProtocolMinor } from './epochParamsItemProtocolMinor';
import type { EpochParamsItemPvtCommitteeNoConfidence } from './epochParamsItemPvtCommitteeNoConfidence';
import { bigIntsEpochParamsItemPvtCommitteeNoConfidence } from './epochParamsItemPvtCommitteeNoConfidence';
import type { EpochParamsItemPvtCommitteeNormal } from './epochParamsItemPvtCommitteeNormal';
import { bigIntsEpochParamsItemPvtCommitteeNormal } from './epochParamsItemPvtCommitteeNormal';
import type { EpochParamsItemPvtHardForkInitiation } from './epochParamsItemPvtHardForkInitiation';
import { bigIntsEpochParamsItemPvtHardForkInitiation } from './epochParamsItemPvtHardForkInitiation';
import type { EpochParamsItemPvtMotionNoConfidence } from './epochParamsItemPvtMotionNoConfidence';
import { bigIntsEpochParamsItemPvtMotionNoConfidence } from './epochParamsItemPvtMotionNoConfidence';
import type { EpochParamsItemPvtppSecurityGroup } from './epochParamsItemPvtppSecurityGroup';
import { bigIntsEpochParamsItemPvtppSecurityGroup } from './epochParamsItemPvtppSecurityGroup';
import type { EpochParamsItemTreasuryGrowthRate } from './epochParamsItemTreasuryGrowthRate';
import { bigIntsEpochParamsItemTreasuryGrowthRate } from './epochParamsItemTreasuryGrowthRate';

export type EpochParamsItem = {
  /** Epoch number */
  epoch_no?: number;
  /** Cardano Era */
  era?: string;
  /** The 'a' parameter to calculate the minimum transaction fee */
  min_fee_a?: EpochParamsItemMinFeeA;
  /** The 'b' parameter to calculate the minimum transaction fee */
  min_fee_b?: EpochParamsItemMinFeeB;
  /** The maximum block size (in bytes) */
  max_block_size?: EpochParamsItemMaxBlockSize;
  /** The maximum transaction size (in bytes) */
  max_tx_size?: EpochParamsItemMaxTxSize;
  /** The maximum block header size (in bytes) */
  max_bh_size?: EpochParamsItemMaxBhSize;
  /** The amount (in number) required for a deposit to register a stake address */
  key_deposit?: EpochParamsItemKeyDeposit;
  /** The amount (in number) required for a deposit to register a stake pool */
  pool_deposit?: EpochParamsItemPoolDeposit;
  /** The maximum number of epochs in the future that a pool retirement is allowed to be scheduled for */
  max_epoch?: EpochParamsItemMaxEpoch;
  /** The optimal number of stake pools */
  optimal_pool_count?: EpochParamsItemOptimalPoolCount;
  /** The pledge influence on pool rewards */
  influence?: EpochParamsItemInfluence;
  /** The monetary expansion rate */
  monetary_expand_rate?: EpochParamsItemMonetaryExpandRate;
  /** The treasury growth rate */
  treasury_growth_rate?: EpochParamsItemTreasuryGrowthRate;
  /** The decentralisation parameter (1 fully centralised, 0 fully decentralised) */
  decentralisation?: EpochParamsItemDecentralisation;
  /** The hash of 32-byte string of extra random-ness added into the protocol's entropy pool */
  extra_entropy?: EpochParamsItemExtraEntropy;
  /** The protocol major version */
  protocol_major?: EpochParamsItemProtocolMajor;
  /** The protocol minor version */
  protocol_minor?: EpochParamsItemProtocolMinor;
  /** The minimum value of a UTxO entry */
  min_utxo_value?: EpochParamsItemMinUtxoValue;
  /** The minimum pool cost */
  min_pool_cost?: EpochParamsItemMinPoolCost;
  /** The nonce value for this epoch */
  nonce?: EpochParamsItemNonce;
  /** The hash of the first block where these parameters are valid */
  block_hash?: string;
  /** The per language cost model in JSON */
  cost_models?: EpochParamsItemCostModels;
  /** The per word cost of script memory usage */
  price_mem?: EpochParamsItemPriceMem;
  /** The cost of script execution step usage */
  price_step?: EpochParamsItemPriceStep;
  /** The maximum number of execution memory allowed to be used in a single transaction */
  max_tx_ex_mem?: EpochParamsItemMaxTxExMem;
  /** The maximum number of execution steps allowed to be used in a single transaction */
  max_tx_ex_steps?: EpochParamsItemMaxTxExSteps;
  /** The maximum number of execution memory allowed to be used in a single block */
  max_block_ex_mem?: EpochParamsItemMaxBlockExMem;
  /** The maximum number of execution steps allowed to be used in a single block */
  max_block_ex_steps?: EpochParamsItemMaxBlockExSteps;
  /** The maximum Val size */
  max_val_size?: EpochParamsItemMaxValSize;
  /** The percentage of the tx fee which must be provided as collateral when including non-native scripts */
  collateral_percent?: EpochParamsItemCollateralPercent;
  /** The maximum number of collateral inputs allowed in a transaction */
  max_collateral_inputs?: EpochParamsItemMaxCollateralInputs;
  /** The cost per UTxO size */
  coins_per_utxo_size?: EpochParamsItemCoinsPerUtxoSize;
  /** Pool Voting threshold for motion of no-confidence. */
  pvt_motion_no_confidence?: EpochParamsItemPvtMotionNoConfidence;
  /** Pool Voting threshold for new committee/threshold (normal state). */
  pvt_committee_normal?: EpochParamsItemPvtCommitteeNormal;
  /** Pool Voting threshold for new committee/threshold (state of no-confidence). */
  pvt_committee_no_confidence?: EpochParamsItemPvtCommitteeNoConfidence;
  /** Pool Voting threshold for hard-fork initiation. */
  pvt_hard_fork_initiation?: EpochParamsItemPvtHardForkInitiation;
  /** DRep Vote threshold for motion of no-confidence. */
  dvt_motion_no_confidence?: EpochParamsItemDvtMotionNoConfidence;
  /** DRep Vote threshold for new committee/threshold (normal state). */
  dvt_committee_normal?: EpochParamsItemDvtCommitteeNormal;
  /** DRep Vote threshold for new committee/threshold (state of no-confidence). */
  dvt_committee_no_confidence?: EpochParamsItemDvtCommitteeNoConfidence;
  /** DRep Vote threshold for update to the Constitution. */
  dvt_update_to_constitution?: EpochParamsItemDvtUpdateToConstitution;
  /** DRep Vote threshold for hard-fork initiation. */
  dvt_hard_fork_initiation?: EpochParamsItemDvtHardForkInitiation;
  /** DRep Vote threshold for protocol parameter changes, network group. */
  dvt_p_p_network_group?: EpochParamsItemDvtPPNetworkGroup;
  /** DRep Vote threshold for protocol parameter changes, economic group. */
  dvt_p_p_economic_group?: EpochParamsItemDvtPPEconomicGroup;
  /** DRep Vote threshold for protocol parameter changes, technical group. */
  dvt_p_p_technical_group?: EpochParamsItemDvtPPTechnicalGroup;
  /** DRep Vote threshold for protocol parameter changes, governance group. */
  dvt_p_p_gov_group?: EpochParamsItemDvtPPGovGroup;
  /** DRep Vote threshold for treasury withdrawal. */
  dvt_treasury_withdrawal?: EpochParamsItemDvtTreasuryWithdrawal;
  /** Minimal constitutional committee size. */
  committee_min_size?: EpochParamsItemCommitteeMinSize;
  /** Constitutional committee term limits. */
  committee_max_term_length?: EpochParamsItemCommitteeMaxTermLength;
  /** Governance action expiration. */
  gov_action_lifetime?: EpochParamsItemGovActionLifetime;
  /** Governance action deposit. */
  gov_action_deposit?: EpochParamsItemGovActionDeposit;
  /** DRep deposit amount. */
  drep_deposit?: EpochParamsItemDrepDeposit;
  /** DRep activity period. */
  drep_activity?: EpochParamsItemDrepActivity;
  /** Pool Voting threshold for protocol parameter changes, security group. */
  pvtpp_security_group?: EpochParamsItemPvtppSecurityGroup;
  /** Minimum Fee for Reference Script cost pre byte */
  min_fee_ref_script_cost_per_byte?: EpochParamsItemMinFeeRefScriptCostPerByte;
};

export const bigIntsEpochParamsItem: Array<string> = [
  ...bigIntsEpochParamsItemMinFeeA.map((item) =>
    item === '' ? 'min_fee_a' : `min_fee_a.${item}`,
  ),
  ...bigIntsEpochParamsItemMinFeeB.map((item) =>
    item === '' ? 'min_fee_b' : `min_fee_b.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxBlockSize.map((item) =>
    item === '' ? 'max_block_size' : `max_block_size.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxTxSize.map((item) =>
    item === '' ? 'max_tx_size' : `max_tx_size.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxBhSize.map((item) =>
    item === '' ? 'max_bh_size' : `max_bh_size.${item}`,
  ),
  ...bigIntsEpochParamsItemKeyDeposit.map((item) =>
    item === '' ? 'key_deposit' : `key_deposit.${item}`,
  ),
  ...bigIntsEpochParamsItemPoolDeposit.map((item) =>
    item === '' ? 'pool_deposit' : `pool_deposit.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxEpoch.map((item) =>
    item === '' ? 'max_epoch' : `max_epoch.${item}`,
  ),
  ...bigIntsEpochParamsItemOptimalPoolCount.map((item) =>
    item === '' ? 'optimal_pool_count' : `optimal_pool_count.${item}`,
  ),
  ...bigIntsEpochParamsItemInfluence.map((item) =>
    item === '' ? 'influence' : `influence.${item}`,
  ),
  ...bigIntsEpochParamsItemMonetaryExpandRate.map((item) =>
    item === '' ? 'monetary_expand_rate' : `monetary_expand_rate.${item}`,
  ),
  ...bigIntsEpochParamsItemTreasuryGrowthRate.map((item) =>
    item === '' ? 'treasury_growth_rate' : `treasury_growth_rate.${item}`,
  ),
  ...bigIntsEpochParamsItemDecentralisation.map((item) =>
    item === '' ? 'decentralisation' : `decentralisation.${item}`,
  ),
  ...bigIntsEpochParamsItemExtraEntropy.map((item) =>
    item === '' ? 'extra_entropy' : `extra_entropy.${item}`,
  ),
  ...bigIntsEpochParamsItemProtocolMajor.map((item) =>
    item === '' ? 'protocol_major' : `protocol_major.${item}`,
  ),
  ...bigIntsEpochParamsItemProtocolMinor.map((item) =>
    item === '' ? 'protocol_minor' : `protocol_minor.${item}`,
  ),
  ...bigIntsEpochParamsItemMinUtxoValue.map((item) =>
    item === '' ? 'min_utxo_value' : `min_utxo_value.${item}`,
  ),
  ...bigIntsEpochParamsItemMinPoolCost.map((item) =>
    item === '' ? 'min_pool_cost' : `min_pool_cost.${item}`,
  ),
  ...bigIntsEpochParamsItemNonce.map((item) =>
    item === '' ? 'nonce' : `nonce.${item}`,
  ),
  ...bigIntsEpochParamsItemCostModels.map((item) =>
    item === '' ? 'cost_models' : `cost_models.${item}`,
  ),
  ...bigIntsEpochParamsItemPriceMem.map((item) =>
    item === '' ? 'price_mem' : `price_mem.${item}`,
  ),
  ...bigIntsEpochParamsItemPriceStep.map((item) =>
    item === '' ? 'price_step' : `price_step.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxTxExMem.map((item) =>
    item === '' ? 'max_tx_ex_mem' : `max_tx_ex_mem.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxTxExSteps.map((item) =>
    item === '' ? 'max_tx_ex_steps' : `max_tx_ex_steps.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxBlockExMem.map((item) =>
    item === '' ? 'max_block_ex_mem' : `max_block_ex_mem.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxBlockExSteps.map((item) =>
    item === '' ? 'max_block_ex_steps' : `max_block_ex_steps.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxValSize.map((item) =>
    item === '' ? 'max_val_size' : `max_val_size.${item}`,
  ),
  ...bigIntsEpochParamsItemCollateralPercent.map((item) =>
    item === '' ? 'collateral_percent' : `collateral_percent.${item}`,
  ),
  ...bigIntsEpochParamsItemMaxCollateralInputs.map((item) =>
    item === '' ? 'max_collateral_inputs' : `max_collateral_inputs.${item}`,
  ),
  ...bigIntsEpochParamsItemCoinsPerUtxoSize.map((item) =>
    item === '' ? 'coins_per_utxo_size' : `coins_per_utxo_size.${item}`,
  ),
  ...bigIntsEpochParamsItemPvtMotionNoConfidence.map((item) =>
    item === ''
      ? 'pvt_motion_no_confidence'
      : `pvt_motion_no_confidence.${item}`,
  ),
  ...bigIntsEpochParamsItemPvtCommitteeNormal.map((item) =>
    item === '' ? 'pvt_committee_normal' : `pvt_committee_normal.${item}`,
  ),
  ...bigIntsEpochParamsItemPvtCommitteeNoConfidence.map((item) =>
    item === ''
      ? 'pvt_committee_no_confidence'
      : `pvt_committee_no_confidence.${item}`,
  ),
  ...bigIntsEpochParamsItemPvtHardForkInitiation.map((item) =>
    item === ''
      ? 'pvt_hard_fork_initiation'
      : `pvt_hard_fork_initiation.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtMotionNoConfidence.map((item) =>
    item === ''
      ? 'dvt_motion_no_confidence'
      : `dvt_motion_no_confidence.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtCommitteeNormal.map((item) =>
    item === '' ? 'dvt_committee_normal' : `dvt_committee_normal.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtCommitteeNoConfidence.map((item) =>
    item === ''
      ? 'dvt_committee_no_confidence'
      : `dvt_committee_no_confidence.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtUpdateToConstitution.map((item) =>
    item === ''
      ? 'dvt_update_to_constitution'
      : `dvt_update_to_constitution.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtHardForkInitiation.map((item) =>
    item === ''
      ? 'dvt_hard_fork_initiation'
      : `dvt_hard_fork_initiation.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtPPNetworkGroup.map((item) =>
    item === '' ? 'dvt_p_p_network_group' : `dvt_p_p_network_group.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtPPEconomicGroup.map((item) =>
    item === '' ? 'dvt_p_p_economic_group' : `dvt_p_p_economic_group.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtPPTechnicalGroup.map((item) =>
    item === '' ? 'dvt_p_p_technical_group' : `dvt_p_p_technical_group.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtPPGovGroup.map((item) =>
    item === '' ? 'dvt_p_p_gov_group' : `dvt_p_p_gov_group.${item}`,
  ),
  ...bigIntsEpochParamsItemDvtTreasuryWithdrawal.map((item) =>
    item === '' ? 'dvt_treasury_withdrawal' : `dvt_treasury_withdrawal.${item}`,
  ),
  ...bigIntsEpochParamsItemCommitteeMinSize.map((item) =>
    item === '' ? 'committee_min_size' : `committee_min_size.${item}`,
  ),
  ...bigIntsEpochParamsItemCommitteeMaxTermLength.map((item) =>
    item === ''
      ? 'committee_max_term_length'
      : `committee_max_term_length.${item}`,
  ),
  ...bigIntsEpochParamsItemGovActionLifetime.map((item) =>
    item === '' ? 'gov_action_lifetime' : `gov_action_lifetime.${item}`,
  ),
  ...bigIntsEpochParamsItemGovActionDeposit.map((item) =>
    item === '' ? 'gov_action_deposit' : `gov_action_deposit.${item}`,
  ),
  ...bigIntsEpochParamsItemDrepDeposit.map((item) =>
    item === '' ? 'drep_deposit' : `drep_deposit.${item}`,
  ),
  ...bigIntsEpochParamsItemDrepActivity.map((item) =>
    item === '' ? 'drep_activity' : `drep_activity.${item}`,
  ),
  ...bigIntsEpochParamsItemPvtppSecurityGroup.map((item) =>
    item === '' ? 'pvtpp_security_group' : `pvtpp_security_group.${item}`,
  ),
  ...bigIntsEpochParamsItemMinFeeRefScriptCostPerByte.map((item) =>
    item === ''
      ? 'min_fee_ref_script_cost_per_byte'
      : `min_fee_ref_script_cost_per_byte.${item}`,
  ),
];
